"""LED Display Leads - Americas + Korea - Full Version v3
Updates from v2:
  - AVAVISION & Shinwoo SNC: added CEO names
  - +4 new Korean companies (Shinelight, SYSMATE, Koled, Asolcompany)
  - +8 new Brazilian companies
  - +9 new USA companies
  Total: ~121 records
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

leads = [
    # ==================== BRAZIL (17 → 25) ====================
    {
        "no":1,"country":"Brazil","region":"South America",
        "company_en":"LedWave","company_local":"LedWave",
        "city":"São Paulo / Goiânia / Rio / Brasília",
        "contact_name":"","title":"",
        "email":"contato@ledwave.com.br",
        "phone_whatsapp":"+55 11 3044-4609 / 0800 943-7800",
        "website":"http://www.ledwave.com.br",
        "business":"LED panel sales, rental, OOH media; B Corp certified",
        "facebook":"facebook.com/ledwavesaopaulo","instagram":"instagram.com/ledwave","linkedin":"linkedin.com/company/ledwave",
    },
    {
        "no":2,"country":"Brazil","region":"South America",
        "company_en":"Crialed Visual Productions","company_local":"Crialed Produções Visuais e Eventos",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@crialed.com.br",
        "phone_whatsapp":"+55 11 2291-0031 / WA: +55 11 95663-5316",
        "website":"https://www.crialed.com.br",
        "business":"LED panel sales, rental & events (since 2008)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":3,"country":"Brazil","region":"South America",
        "company_en":"LED 10","company_local":"LED 10",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@led10.com.br",
        "phone_whatsapp":"+55 11 2115-3091",
        "website":"http://led10.com.br",
        "business":"LED panel sales & rental (since 2010)",
        "facebook":"facebook.com/paineisled10","instagram":"","linkedin":"",
    },
    {
        "no":4,"country":"Brazil","region":"South America",
        "company_en":"P1LED / Prime LED","company_local":"P1LED / Prime Led",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@p1led.com.br",
        "phone_whatsapp":"+55 11 2626-2460 / WA: +55 11 99137-8503",
        "website":"https://www.primeled.com.br",
        "business":"LED panel pioneer, retail + commercial, 15+ years; reseller program",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":5,"country":"Brazil","region":"South America",
        "company_en":"The LED","company_local":"The LED",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"comercial@theled.com.br",
        "phone_whatsapp":"+55 11 98940-4332 / +55 11 96334-5500",
        "website":"http://www.theled.com.br",
        "business":"Largest LED visual communications company in Brazil; distributor network",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":6,"country":"Brazil","region":"South America",
        "company_en":"Dshow","company_local":"Dshow",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"dshow@dshow.com.br",
        "phone_whatsapp":"+55 11 99714-4969 / +55 11 3392-1514",
        "website":"http://www.dshow.com.br",
        "business":"Indoor/outdoor/flexible LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":7,"country":"Brazil","region":"South America",
        "company_en":"NA Equipment","company_local":"N.A. Equipamentos",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"orcamentos1@naequipamentos.com.br",
        "phone_whatsapp":"+55 11 3606-7878",
        "website":"http://www.naequipamentos.com.br",
        "business":"Full-color LED panels + professional video equipment",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":8,"country":"Brazil","region":"South America",
        "company_en":"Nationstar Brasil","company_local":"Nationstar Brasil",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"vendas@nationstar.com.br",
        "phone_whatsapp":"+55 11 58974392",
        "website":"https://www.nationstarbrasil.com.br",
        "business":"Full-color LED panel supplier",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":9,"country":"Brazil","region":"South America",
        "company_en":"Optiart","company_local":"Optiart",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"comercial@optiart.com.br",
        "phone_whatsapp":"+55 11 5060-4140",
        "website":"https://optiart.com.br",
        "business":"Retail digital signage & LED; official Samsung distributor in Brazil",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":10,"country":"Brazil","region":"South America",
        "company_en":"Elite LED","company_local":"Elite LED",
        "city":"Rio de Janeiro, RJ",
        "contact_name":"","title":"",
        "email":"contato@eliteled.com.br",
        "phone_whatsapp":"+55 21 3344-0206",
        "website":"https://eliteled.com.br",
        "business":"Exclusive distributor for PROMARC LED screens in Brazil",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":11,"country":"Brazil","region":"South America",
        "company_en":"Mundo de LED","company_local":"Mundo de LED",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"sales@mundodeled.com.br",
        "phone_whatsapp":"(88) 99605-3355",
        "website":"https://www.mundodeled.com.br",
        "business":"LED display sales & distribution (since 2013)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":12,"country":"Brazil","region":"South America",
        "company_en":"Innovate Brazil","company_local":"Innovate Brasil",
        "city":"Guarapari, ES",
        "contact_name":"","title":"",
        "email":"contato@innovatebrazil.com.br",
        "phone_whatsapp":"+55 27 3362-1614",
        "website":"https://innovatebrazil.com.br",
        "business":"LED panel manufacturer & retailer, 3-yr warranty, national delivery",
        "facebook":"","instagram":"instagram.com/innovatebrazil","linkedin":"",
    },
    {
        "no":13,"country":"Brazil","region":"South America",
        "company_en":"IDEA LED Panels","company_local":"IDEA Painéis de LED",
        "city":"Caxias do Sul, RS",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"(54) 3025-2921 / WA: wa.link/7jz8hw",
        "website":"https://www.paineldeled.com",
        "business":"LED panel supplier, 20 years, premium quality, B2B reseller-focused",
        "facebook":"facebook.com/ideapaineisdeled","instagram":"instagram.com/ideapaineisdeled","linkedin":"linkedin.com/in/idea-painéis-de-led",
    },
    {
        "no":14,"country":"Brazil","region":"South America",
        "company_en":"NN LED","company_local":"NN LED",
        "city":"Campinas, SP",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"WA: (19) 99762-6990",
        "website":"",
        "business":"LED panel (P4) rental & LED robot; events",
        "facebook":"facebook.com/nnled","instagram":"","linkedin":"",
    },
    {
        "no":15,"country":"Brazil","region":"South America",
        "company_en":"Power LED","company_local":"Power Led",
        "city":"Campinas, SP",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"(19) 3365-1636 / WA: (19) 99901-2883",
        "website":"",
        "business":"LED panel sales & rental",
        "facebook":"facebook.com/powerproled","instagram":"","linkedin":"",
    },
    {
        "no":16,"country":"Brazil","region":"South America",
        "company_en":"Rangel Panels","company_local":"Rangel Painéis",
        "city":"São Paulo, SP",
        "contact_name":"Flávio","title":"Owner",
        "email":"flavio@rangelpaineis.com.br",
        "phone_whatsapp":"+55 11 99995-6612",
        "website":"https://rangelpaineis.com.br",
        "business":"LED display & advertising panels (since 1998)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":17,"country":"Brazil","region":"South America",
        "company_en":"Trend LED","company_local":"Trend Led",
        "city":"Brasília, DF",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED panel rental & sales",
        "facebook":"facebook.com/Trendbsb","instagram":"","linkedin":"",
    },
    # --- New Brazil companies ---
    {
        "no":18,"country":"Brazil","region":"South America",
        "company_en":"Rogustec","company_local":"Rogustec",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"atendimento@rogustec.com.br",
        "phone_whatsapp":"+55 11 5525-1399",
        "website":"https://rogustec.com.br",
        "business":"LED display & digital signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":19,"country":"Brazil","region":"South America",
        "company_en":"Aloc LED","company_local":"Aloc",
        "city":"Belo Horizonte, MG",
        "contact_name":"","title":"",
        "email":"belohorizonte@aloc.com.br",
        "phone_whatsapp":"(31) 3058-0600",
        "website":"https://aloc.com.br",
        "business":"LED display & professional AV equipment",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":20,"country":"Brazil","region":"South America",
        "company_en":"TOPLED Multimidia","company_local":"TOPLED",
        "city":"Goiânia, GO",
        "contact_name":"","title":"",
        "email":"contato@topledmultimidia.com.br",
        "phone_whatsapp":"(62) 3099-3817",
        "website":"https://topledmultimidia.com.br",
        "business":"LED multimedia panel sales & rental (Goiânia region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":21,"country":"Brazil","region":"South America",
        "company_en":"LATINLED","company_local":"LATINLED",
        "city":"Florianópolis, SC",
        "contact_name":"","title":"",
        "email":"info@latinled.com.br",
        "phone_whatsapp":"+55 48 9115-2071",
        "website":"https://latinled.com.br",
        "business":"LED display wholesale & distribution",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":22,"country":"Brazil","region":"South America",
        "company_en":"PLL Painéis","company_local":"PLL Painéis",
        "city":"Brazil",
        "contact_name":"Carlos","title":"Sales",
        "email":"carlos@pllpaineis.com.br",
        "phone_whatsapp":"",
        "website":"",
        "business":"LED panel distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":23,"country":"Brazil","region":"South America",
        "company_en":"All Trading","company_local":"All Trading",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"comercial@alltrading.com.br",
        "phone_whatsapp":"(11) 98477-0223",
        "website":"",
        "business":"LED display trading & import",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":24,"country":"Brazil","region":"South America",
        "company_en":"Qualipix Video Wall","company_local":"Video Wall BH / Qualipix",
        "city":"Belo Horizonte, MG",
        "contact_name":"","title":"",
        "email":"contato@qualipix.com.br",
        "phone_whatsapp":"(31) 3568-6835",
        "website":"",
        "business":"LED video wall installation & sales",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":25,"country":"Brazil","region":"South America",
        "company_en":"Pantallas Brasil LED","company_local":"Pantallas Brasil LED",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@pantallasbrasil.com.br",
        "phone_whatsapp":"+55 11 97640-6060",
        "website":"https://pantallasbrasil.com.br",
        "business":"LED screen distributor, indoor/outdoor advertising",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== COLOMBIA (5) ====================
    {
        "no":26,"country":"Colombia","region":"South America",
        "company_en":"PubliMaster Colombia","company_local":"Publi Master SJ",
        "city":"Medellín",
        "contact_name":"","title":"",
        "email":"ventas@publimastercolombia.com",
        "phone_whatsapp":"+57 311 2419363",
        "website":"https://publimastercolombia.com",
        "business":"LED screen importer & commercializer; events/indoor/outdoor advertising",
        "facebook":"facebook.com/publimasterSJ","instagram":"instagram.com/publimastersj","linkedin":"",
    },
    {
        "no":27,"country":"Colombia","region":"South America",
        "company_en":"Digital Signage Colombia","company_local":"Digital Signage Colombia SAS",
        "city":"Bogotá",
        "contact_name":"","title":"",
        "email":"negocios@dscolombia.co",
        "phone_whatsapp":"601 4321929 / WA: +57 317 521 1104",
        "website":"https://dscolombia.co",
        "business":"Official Samsung distributor (Colombia); LED video wall, touch screens; 15+ yrs",
        "facebook":"facebook.com/DigitalSignageColombia","instagram":"instagram.com/digitalsignagecolombia","linkedin":"linkedin.com/company/digital-signage-colombia-sas",
    },
    {
        "no":28,"country":"Colombia","region":"South America",
        "company_en":"MachineTronics","company_local":"MachineTronics",
        "city":"Bogotá / Medellín / Cali",
        "contact_name":"Yulieth Cruz","title":"",
        "email":"","phone_whatsapp":"+57 318 3400796 / +57 316 4086143",
        "website":"https://www.machinetronics.com",
        "business":"LED screen manufacturer & distributor; advertising/events/real estate/corporate",
        "facebook":"facebook.com/MachineTronics","instagram":"","linkedin":"linkedin.com/in/yulieth-cruz-145a784a",
    },
    {
        "no":29,"country":"Colombia","region":"South America",
        "company_en":"InOut Soluciones","company_local":"InOut Soluciones",
        "city":"Bogotá",
        "contact_name":"","title":"",
        "email":"info@inoutsoluciones.com",
        "phone_whatsapp":"+57 312 356 9648",
        "website":"https://www.inoutsoluciones.com",
        "business":"LED wall manufacturer; indoor/outdoor; offices/malls/education; 15+ yrs",
        "facebook":"","instagram":"instagram.com/inoutsoluciones","linkedin":"linkedin.com/company/inout-soluciones",
    },
    {
        "no":30,"country":"Colombia","region":"South America",
        "company_en":"Visual Led Colombia","company_local":"Visual Led Colombia",
        "city":"Colombia",
        "contact_name":"","title":"",
        "email":"ventas@visualled.com","phone_whatsapp":"",
        "website":"https://visualled.com",
        "business":"LED screen design & manufacturing for indoor/outdoor advertising (since 2003)",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== CHILE (9) ====================
    {
        "no":31,"country":"Chile","region":"South America",
        "company_en":"PLED Chile","company_local":"PLED.cl",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@pled.cl","phone_whatsapp":"+56 9 3659-1068",
        "website":"https://www.pled.cl",
        "business":"LED display sales & rental",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":32,"country":"Chile","region":"South America",
        "company_en":"Tecnogroup Chile","company_local":"Tecnogroup",
        "city":"Las Condes, Santiago",
        "contact_name":"","title":"",
        "email":"contacto@tecnogroup.cl","phone_whatsapp":"+56 9 5449-1032",
        "website":"https://tecnogroup.cl",
        "business":"LED display & tech solutions; retail nationwide",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":33,"country":"Chile","region":"South America",
        "company_en":"Led Neon Chile","company_local":"Led Neon Chile (LNC)",
        "city":"Renca, Santiago",
        "contact_name":"","title":"",
        "email":"ventas@lnc.cl","phone_whatsapp":"+56 2 2957-4444",
        "website":"https://www.lnc.cl",
        "business":"LED display & neon, 30 years experience; electronic displays",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":34,"country":"Chile","region":"South America",
        "company_en":"Remote Media","company_local":"Remote Media",
        "city":"Ñuñoa, Santiago",
        "contact_name":"","title":"",
        "email":"info@remotemedia.cl","phone_whatsapp":"+56 2 2352-5532",
        "website":"https://remotemedia.cl",
        "business":"Digital signage & LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":35,"country":"Chile","region":"South America",
        "company_en":"Fullvision","company_local":"Fullvision",
        "city":"Ñuñoa, Santiago",
        "contact_name":"","title":"",
        "email":"info@fullvision.cl","phone_whatsapp":"+56 2 2455-6596",
        "website":"https://www.fullvision.cl",
        "business":"LED display system integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":36,"country":"Chile","region":"South America",
        "company_en":"Demco Ltda","company_local":"Demco Ltda",
        "city":"Quilicura, Santiago",
        "contact_name":"","title":"",
        "email":"info@demco.cl","phone_whatsapp":"+56 2 2782-1800",
        "website":"https://www.demco.cl",
        "business":"Wholesale distributor (since 1983); LED/AV products",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":37,"country":"Chile","region":"South America",
        "company_en":"4D LED Screens","company_local":"4D Pantallas LEAD",
        "city":"Las Condes, Santiago",
        "contact_name":"","title":"",
        "email":"info@cuatrod.net","phone_whatsapp":"+56 2 434-1800",
        "website":"https://www.cuatrod.net",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":38,"country":"Chile","region":"South America",
        "company_en":"VideoWall Corporation","company_local":"VideoWall Corporation SPA",
        "city":"La Reina, Santiago",
        "contact_name":"","title":"",
        "email":"info@videowall.cl","phone_whatsapp":"+56 9 8808-3220",
        "website":"https://www.videowall.cl",
        "business":"LED video wall systems integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":39,"country":"Chile","region":"South America",
        "company_en":"Cleverox","company_local":"Cleverox",
        "city":"Huechuraba, Santiago",
        "contact_name":"","title":"",
        "email":"contacto@cleverox.com","phone_whatsapp":"+56 2 2956-3200",
        "website":"https://www.cleverox.com",
        "business":"LED display & AV integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== PERU (10) ====================
    {
        "no":40,"country":"Peru","region":"South America",
        "company_en":"EXCTECLED Peru","company_local":"Pantallas LED Peru - EXCTECLED",
        "city":"San Isidro, Lima",
        "contact_name":"","title":"",
        "email":"ventas@exctecled.com","phone_whatsapp":"+51 913059191",
        "website":"https://exctecled.com",
        "business":"Leading LED advertising screen distributor in Peru; fixed/rental/stadium",
        "facebook":"facebook.com/exctecled","instagram":"instagram.com/pantallasledperu","linkedin":"",
    },
    {
        "no":41,"country":"Peru","region":"South America",
        "company_en":"LED Laser Peru","company_local":"LED y Laser Peru",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@ledylaserperu.com","phone_whatsapp":"+51 933 488 195",
        "website":"https://ledylaserperu.com",
        "business":"LED display sales & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":42,"country":"Peru","region":"South America",
        "company_en":"BiG LED Peru","company_local":"BiG LED",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@bigledperu.com","phone_whatsapp":"+51 944 570 337",
        "website":"https://www.bigledperu.com",
        "business":"LED display wholesale & retail",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":43,"country":"Peru","region":"South America",
        "company_en":"Layset Peru","company_local":"Layset",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@layset2.com","phone_whatsapp":"+51 999 518 109",
        "website":"https://www.layset2.com",
        "business":"LED screen distributor, 15+ years",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":44,"country":"Peru","region":"South America",
        "company_en":"Orion Enterprises Peru","company_local":"ORION ENTERPRISES",
        "city":"Miraflores, Lima",
        "contact_name":"","title":"",
        "email":"info@orion-peru.com","phone_whatsapp":"+51 989 153 655",
        "website":"https://orion-peru.com",
        "business":"LED display solutions & integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":45,"country":"Peru","region":"South America",
        "company_en":"NeoLED Peru","company_local":"NEOLEDPERU",
        "city":"Los Olivos, Lima",
        "contact_name":"","title":"",
        "email":"info@neoledperu.com","phone_whatsapp":"+51 43 221 254",
        "website":"https://www.neoledperu.com",
        "business":"LED display sales & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":46,"country":"Peru","region":"South America",
        "company_en":"LED Maker Peru","company_local":"LED MAKER",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@ledmaker.com.pe","phone_whatsapp":"+51 967 645 520",
        "website":"https://ledmaker.com.pe",
        "business":"LED display manufacturer & supplier",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":47,"country":"Peru","region":"South America",
        "company_en":"INNOVALED Peru","company_local":"INNOVALED",
        "city":"Surquillo, Lima",
        "contact_name":"","title":"",
        "email":"ventas@innovaled.pe","phone_whatsapp":"+51 986 534 469",
        "website":"https://www.innovaled.pe",
        "business":"LED display innovation & sales",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":48,"country":"Peru","region":"South America",
        "company_en":"Goled Peru","company_local":"Goled Peru",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@goledperu.com","phone_whatsapp":"+51 1 639-6589",
        "website":"http://goledperu.com",
        "business":"14 years professional LED display & solar installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":49,"country":"Peru","region":"South America",
        "company_en":"Lontec Peru","company_local":"Lontec",
        "city":"La Perla, Callao",
        "contact_name":"","title":"",
        "email":"ventas@lontecperu.com","phone_whatsapp":"+51 914 968 151",
        "website":"https://lontecperu.com",
        "business":"LED display distributor & installer",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== ARGENTINA (10) ====================
    {
        "no":50,"country":"Argentina","region":"South America",
        "company_en":"Dinalight","company_local":"Dinalight",
        "city":"Buenos Aires (Franklin D. Roosevelt 3644)",
        "contact_name":"","title":"",
        "email":"info@dinalight.com",
        "phone_whatsapp":"+54 9 11 4064-9989 / WA: +54 9 11 3848-0840",
        "website":"https://www.dinalight.com",
        "business":"LED manufacturer 20+ yrs; indoor/outdoor/rental/mesh; expands across LatAm",
        "facebook":"facebook.com/p/Dinalightlatam-100072348303065","instagram":"instagram.com/dinalight.led","linkedin":"",
    },
    {
        "no":51,"country":"Argentina","region":"South America",
        "company_en":"Grupo UNO LED","company_local":"Grupo UNO LED",
        "city":"Martín Coronado, Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@grupounoled.com","phone_whatsapp":"+54 9 11 5740-6998",
        "website":"https://grupounoled.com",
        "business":"Argentine LED screen factory, 3000+ clients; outdoor/indoor/mobile + G1 Studio CMS",
        "facebook":"facebook.com/grupounoled","instagram":"instagram.com/grupounoled","linkedin":"",
    },
    {
        "no":52,"country":"Argentina","region":"South America",
        "company_en":"Multiled","company_local":"Multiled",
        "city":"Buenos Aires (Salta 285)",
        "contact_name":"","title":"",
        "email":"info@multiled.com.ar","phone_whatsapp":"4373-9500",
        "website":"https://www.multiled.com.ar",
        "business":"Advertising LED screens, marketing panels, industrial",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":53,"country":"Argentina","region":"South America",
        "company_en":"Microled Argentina","company_local":"Microled Argentina",
        "city":"CABA (Pichincha 188)",
        "contact_name":"","title":"",
        "email":"info@microled.com.ar","phone_whatsapp":"+54 11 4954-0056",
        "website":"https://microled.com.ar",
        "business":"LED signage & display",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":54,"country":"Argentina","region":"South America",
        "company_en":"Tecnoled Argentina","company_local":"Tecnoled",
        "city":"Tigre, Buenos Aires",
        "contact_name":"","title":"",
        "email":"ventas@tecnoled.ar","phone_whatsapp":"+54 9 11 6488-4200",
        "website":"https://tecnoled.ar",
        "business":"LED screens, digital signage, visual solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":55,"country":"Argentina","region":"South America",
        "company_en":"Grafica LED","company_local":"Gráfica Led",
        "city":"Villa Martelli, Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@graficaled.com","phone_whatsapp":"+54 9 11 3524-9417",
        "website":"https://www.graficaled.com",
        "business":"LED screen rental & fixed installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":56,"country":"Argentina","region":"South America",
        "company_en":"Street LED Argentina","company_local":"Street Led Argentina",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@streetled.com.ar","phone_whatsapp":"+54 11 2187-9006",
        "website":"https://streetled.com.ar",
        "business":"Indoor/outdoor LED screens",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":57,"country":"Argentina","region":"South America",
        "company_en":"Led HD Argentina","company_local":"Led HD",
        "city":"Lomas de Zamora, Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@ledhd.com.ar","phone_whatsapp":"+54 11 2356-3301",
        "website":"https://ledhd.com.ar",
        "business":"HD LED screens, active displays",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":58,"country":"Argentina","region":"South America",
        "company_en":"VDS Argentina","company_local":"VDS",
        "city":"CABA",
        "contact_name":"","title":"",
        "email":"vds@vds.com.ar","phone_whatsapp":"+54 9 11 6094-3669",
        "website":"https://www.vds.com.ar",
        "business":"Rental LED screens & video walls",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":59,"country":"Argentina","region":"South America",
        "company_en":"Altavista LED","company_local":"Altavista LED",
        "city":"Córdoba",
        "contact_name":"","title":"",
        "email":"info@altavistaled.com","phone_whatsapp":"+54 351 254 5609",
        "website":"https://altavistaled.com",
        "business":"Advertising LED screens, DOOH advertising",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== USA (11 → 20) ====================
    {
        "no":60,"country":"USA","region":"North America",
        "company_en":"American LED Display Solutions","company_local":"American LED Display Solutions Corp.",
        "city":"Miami, FL",
        "contact_name":"","title":"",
        "email":"Info@americanledisplays.com",
        "phone_whatsapp":"+1 305-420-5631 / +1 786-228-9212",
        "website":"https://americanledisplays.com",
        "business":"LED visual display mfg/supplier; indoor/outdoor/sports/transparent; global distribution",
        "facebook":"facebook.com/AmericanLedDisplays","instagram":"instagram.com/americanledisplays","linkedin":"linkedin.com/in/american-led-display-solutions-0a116519",
    },
    {
        "no":61,"country":"USA","region":"North America",
        "company_en":"Fusion LED","company_local":"Fusion LED Inc.",
        "city":"Houston, TX",
        "contact_name":"Richard James / Darick Endecott","title":"Founders",
        "email":"sales@fusionled.us","phone_whatsapp":"+1 800-854-6265",
        "website":"https://fusionled.us",
        "business":"LED sign manufacturer; B2B wholesale to sign companies; 1000+ installs",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":62,"country":"USA","region":"North America",
        "company_en":"American LED Technology","company_local":"American LED Technology",
        "city":"North Little Rock, AR",
        "contact_name":"","title":"",
        "email":"info@americanledtechnology.com","phone_whatsapp":"+1 850-863-8777",
        "website":"https://www.americanledtechnology.com",
        "business":"LED display manufacturer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":63,"country":"USA","region":"North America",
        "company_en":"Vanguard LED Displays","company_local":"Vanguard LED Displays",
        "city":"Lakeland, FL",
        "contact_name":"","title":"",
        "email":"info@vanguardled.com","phone_whatsapp":"+1 877-230-8787",
        "website":"https://vanguardled.com",
        "business":"LED display distributor & installer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":64,"country":"USA","region":"North America",
        "company_en":"Aurora LED Systems","company_local":"Aurora LED, LLC",
        "city":"Henderson / Las Vegas, NV",
        "contact_name":"","title":"",
        "email":"info@auroraled.com","phone_whatsapp":"+1 702-386-1088",
        "website":"https://auroraledsystems.com",
        "business":"LED video display; sells to Resellers & Integrators across US & Western Hemisphere",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":65,"country":"USA","region":"North America",
        "company_en":"RP Visual Solutions","company_local":"RP Visual Solutions",
        "city":"Anaheim, CA",
        "contact_name":"","title":"",
        "email":"sales@rpvisuals.com","phone_whatsapp":"+1 714-991-6400",
        "website":"https://rpvisuals.com",
        "business":"LED display & AV visual solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":66,"country":"USA","region":"North America",
        "company_en":"King Size LED","company_local":"King Size LED",
        "city":"Chula Vista, CA",
        "contact_name":"","title":"",
        "email":"info@kingsizeled.com","phone_whatsapp":"+1 619-216-4770",
        "website":"https://www.kingsizeled.com",
        "business":"Large-format LED displays",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":67,"country":"USA","region":"North America",
        "company_en":"LED Craft","company_local":"LED Craft Inc.",
        "city":"St. Louis, MO",
        "contact_name":"","title":"",
        "email":"info@ledcraftinc.com","phone_whatsapp":"+1 314-776-2909",
        "website":"https://www.ledcraftinc.com",
        "business":"LED display manufacturer & distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":68,"country":"USA","region":"North America",
        "company_en":"SNA Displays","company_local":"SNA Displays",
        "city":"New York, NY",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+1 866-848-9149",
        "website":"https://snadisplays.com",
        "business":"Large-scale LED display systems integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":69,"country":"USA","region":"North America",
        "company_en":"PixelFLEX LED","company_local":"PixelFLEX",
        "city":"Nashville, TN",
        "contact_name":"","title":"",
        "email":"sales@pixel-flex.com","phone_whatsapp":"+1 800-930-7954",
        "website":"https://www.pixel-flex.com",
        "business":"Flexible & fine-pitch LED display solutions; entertainment/retail/corporate",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":70,"country":"USA","region":"North America",
        "company_en":"Neoti","company_local":"Neoti",
        "city":"Sioux Falls, SD",
        "contact_name":"","title":"",
        "email":"info@neoti.com","phone_whatsapp":"+1 877-356-3684",
        "website":"https://neoti.com",
        "business":"LED display manufacturer for retail/corporate/broadcast/entertainment",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":71,"country":"USA","region":"North America",
        "company_en":"Formetco","company_local":"Formetco",
        "city":"Duluth, GA",
        "contact_name":"","title":"",
        "email":"sales@formetco.com","phone_whatsapp":"+1 770-476-7000",
        "website":"https://formetco.com",
        "business":"Outdoor LED billboard & digital signage manufacturer (50+ years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":72,"country":"USA","region":"North America",
        "company_en":"NanoLumens","company_local":"NanoLumens",
        "city":"Peachtree Corners, GA",
        "contact_name":"","title":"",
        "email":"info@nanolumens.com","phone_whatsapp":"+1 855-465-8895",
        "website":"https://nanolumens.com",
        "business":"Seamless LED display solutions; retail/hospitality/corporate",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":73,"country":"USA","region":"North America",
        "company_en":"American LED Wall","company_local":"American LED Wall",
        "city":"Houston, TX",
        "contact_name":"","title":"",
        "email":"sales@americanledwall.com","phone_whatsapp":"713-887-2805",
        "website":"https://americanledwall.com",
        "business":"LED video wall sales & installation; events/retail/outdoor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":74,"country":"USA","region":"North America",
        "company_en":"Ultravision LED Solutions","company_local":"Ultravision",
        "city":"Dallas, TX",
        "contact_name":"","title":"",
        "email":"sales@uvledsol.com","phone_whatsapp":"214-504-2404",
        "website":"https://uvledsol.com",
        "business":"Outdoor LED billboard & signage manufacturer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":75,"country":"USA","region":"North America",
        "company_en":"Watchfire Signs","company_local":"Watchfire",
        "city":"Danville, IL",
        "contact_name":"","title":"",
        "email":"sales@watchfire.com","phone_whatsapp":"800-637-2645",
        "website":"https://watchfiresigns.com",
        "business":"LED sign & billboard manufacturer; business/sports/church/transportation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":76,"country":"USA","region":"North America",
        "company_en":"SunRise LED","company_local":"SunRise LED",
        "city":"USA",
        "contact_name":"","title":"",
        "email":"info@sunriseled.com","phone_whatsapp":"800-660-4414",
        "website":"https://sunriseled.com",
        "business":"LED display solutions provider",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":77,"country":"USA","region":"North America",
        "company_en":"Vantage LED","company_local":"Vantage LED",
        "city":"Ontario, CA",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"888-595-3956",
        "website":"https://vantageled.com",
        "business":"Outdoor LED digital signage manufacturer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":78,"country":"USA","region":"North America",
        "company_en":"Advision LED Signs","company_local":"Advision LED Signs",
        "city":"Oakdale, CA",
        "contact_name":"","title":"",
        "email":"contact@advisionledsigns.com","phone_whatsapp":"+1 877-532-5593",
        "website":"https://advisionledsigns.com",
        "business":"LED sign solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":79,"country":"USA","region":"North America",
        "company_en":"Cirrus LED","company_local":"Cirrusled",
        "city":"Portsmouth, NH",
        "contact_name":"","title":"",
        "email":"info@cirrusled.com","phone_whatsapp":"+1 877-636-2331",
        "website":"https://www.cirrusled.com",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== CANADA (1) ====================
    {
        "no":80,"country":"Canada","region":"North America",
        "company_en":"Christie Digital Systems","company_local":"Christie Digital Systems",
        "city":"Kitchener, ON",
        "contact_name":"","title":"",
        "email":"info@christiedigital.com","phone_whatsapp":"+1 714-527-7056",
        "website":"https://www.christiedigital.com",
        "business":"Large-format display & video wall mfg; wholesale to resellers/integrators",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== MEXICO (12) ====================
    {
        "no":81,"country":"Mexico","region":"North America",
        "company_en":"RGB Tronics","company_local":"RGB Tronics",
        "city":"Monterrey, NL",
        "contact_name":"","title":"",
        "email":"info@rgbtronics.com.mx","phone_whatsapp":"+52 81 1772-4695",
        "website":"https://rgbtronics.com.mx",
        "business":"Giant LED screen wholesale & retail, 10+ years",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":82,"country":"Mexico","region":"North America",
        "company_en":"DMX Technologies","company_local":"DMX TEC",
        "city":"Mexico City",
        "contact_name":"","title":"",
        "email":"info@dmxtec.com","phone_whatsapp":"+52 55 5662-2600",
        "website":"https://pantallasled.mx",
        "business":"Large-scale LED electronic screen wholesaler, 10+ years",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":83,"country":"Mexico","region":"North America",
        "company_en":"iLED Mexico","company_local":"iLED Mexico",
        "city":"Monterrey, NL",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+52 81 1101-5015",
        "website":"https://www.iled.com.mx",
        "business":"Giant advertising screens: curved/outdoor/mobile; engineering/installation/maintenance",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":84,"country":"Mexico","region":"North America",
        "company_en":"Medios Mexico","company_local":"Medios México",
        "city":"Naucalpan, Estado de Mexico",
        "contact_name":"","title":"",
        "email":"info@mediosmexico.com","phone_whatsapp":"+52 55 5293-2000",
        "website":"http://mediosmexico.com",
        "business":"LED screen commercialization, manufacturing & outdoor digital advertising, 10+ yrs",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":85,"country":"Mexico","region":"North America",
        "company_en":"HPMLED / Grupo Vision","company_local":"HPMLED",
        "city":"Apodaca, Nuevo León",
        "contact_name":"","title":"",
        "email":"aguzman@grupovision.com.mx","phone_whatsapp":"+52 81 1158-5800",
        "website":"https://hpmled.com.mx",
        "business":"LED display solutions, industrial park",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":86,"country":"Mexico","region":"North America",
        "company_en":"Pixel Window Mexico","company_local":"Pixelwindow",
        "city":"Zapopan, Jalisco",
        "contact_name":"E. Barón","title":"",
        "email":"ebaron@pixelwindow.com.mx","phone_whatsapp":"+52 442 456-4968",
        "website":"https://www.pixelwindow.com.mx",
        "business":"LED display manufacturer; CDMX / Querétaro / Guadalajara offices",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":87,"country":"Mexico","region":"North America",
        "company_en":"Showco Mexico","company_local":"Showco",
        "city":"Naucalpan, Estado de Mexico",
        "contact_name":"","title":"",
        "email":"info@showco.com.mx","phone_whatsapp":"+52 55 5000-9480",
        "website":"https://www.showco.com.mx",
        "business":"LED screens, events & AV",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":88,"country":"Mexico","region":"North America",
        "company_en":"MAX Signage Mexico","company_local":"MAX Signage",
        "city":"Mexico City",
        "contact_name":"Ricardo Zepeda","title":"",
        "email":"ricardo.zepeda@max-signage.com.mx","phone_whatsapp":"+52 55 5021-3584",
        "website":"https://max-signage.com.mx",
        "business":"LED signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":89,"country":"Mexico","region":"North America",
        "company_en":"Luft Screen","company_local":"Luft Screen",
        "city":"Iztacalco, CDMX",
        "contact_name":"","title":"",
        "email":"informes@luftscreen.com.mx","phone_whatsapp":"+52 1 55 2335-3227",
        "website":"https://luftscreen.com.mx",
        "business":"LED screen solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":90,"country":"Mexico","region":"North America",
        "company_en":"SAP LED","company_local":"SAP LED",
        "city":"San Luis Potosí",
        "contact_name":"","title":"",
        "email":"contacto@sapled.mx","phone_whatsapp":"+52 444 210-0824",
        "website":"https://sapled.mx",
        "business":"LED display distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":91,"country":"Mexico","region":"North America",
        "company_en":"Eyecatch Mexico","company_local":"Eyecatch Mexico",
        "city":"Mexico City",
        "contact_name":"Eduardo Rosales","title":"",
        "email":"eduardo.rosales@eyecatch.mx","phone_whatsapp":"+52 56 1004-6498",
        "website":"https://eyecatch.mx",
        "business":"LED display & digital signage",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":92,"country":"Mexico","region":"North America",
        "company_en":"MMP Screen","company_local":"MMP Screen",
        "city":"Roma Sur, CDMX",
        "contact_name":"","title":"",
        "email":"info@mmp.com.mx","phone_whatsapp":"+52 55 5412-0445",
        "website":"https://mmp.com.mx",
        "business":"LED screen solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== KOREA (25 → 35, updated + new) ====================
    {
        "no":93,"country":"Korea","region":"Asia",
        "company_en":"RGB Korea","company_local":"RGB Korea / RGB코리아",
        "city":"Siheung, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"amnite@naver.com","phone_whatsapp":"+82 31 504-3773",
        "website":"https://rgbkorea.com",
        "business":"Transparent LED screen, LED lighting, media facade, theme park lighting",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":94,"country":"Korea","region":"Asia",
        "company_en":"MD LED Innovation","company_local":"MD LED 이노베이션",
        "city":"Hwaseong, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"mdledinnovation@naver.com","phone_whatsapp":"+82 31 356-1121",
        "website":"https://www.mdledinnovation.com",
        "business":"Indoor/outdoor/vehicle/hologram/transparent/media facade LED (since 1990)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":95,"country":"Korea","region":"Asia",
        "company_en":"Galaxia Electronics","company_local":"갤럭시아일렉트로닉스",
        "city":"Suwon, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 31 806-0897",
        "website":"https://eng.galaxialed.com",
        "business":"LED display manufacturer (since 2014)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":96,"country":"Korea","region":"Asia",
        "company_en":"KODICO","company_local":"코디코",
        "city":"Ansan, Gyeonggi-do",
        "contact_name":"Thomas Yoo","title":"International Sales",
        "email":"Thomas.yoo@kodico.co.kr","phone_whatsapp":"+82 70 4681-6149",
        "website":"https://kodico.co.kr/eng",
        "business":"LED display solutions (since 1990)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":97,"country":"Korea","region":"Asia",
        "company_en":"Kinoton Korea","company_local":"키노톤코리아",
        "city":"Seoul (Seocho-gu)",
        "contact_name":"","title":"",
        "email":"biz@kinoton.co.kr","phone_whatsapp":"+82 2 6923-1900",
        "website":"https://kinoton.co.kr",
        "business":"LED/video/digital media/audio solutions; cinema & events",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":98,"country":"Korea","region":"Asia",
        "company_en":"Samik Electronics","company_local":"삼익전자",
        "city":"Seoul (Gangnam-gu)",
        "contact_name":"","title":"",
        "email":"samilk@samikdisplay.co.kr","phone_whatsapp":"+82 2 510-2000",
        "website":"https://samikdisplay.co.kr",
        "business":"LED display pioneer in Korea (since 1969); indoor/outdoor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":99,"country":"Korea","region":"Asia",
        "company_en":"ARA System","company_local":"아라시스템",
        "city":"Anyang, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"info@arasystem.kr","phone_whatsapp":"+82 70 4895-0794",
        "website":"https://arasystem.kr",
        "business":"LED display system integrator (since 2007)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":100,"country":"Korea","region":"Asia",
        "company_en":"ShownProbe","company_local":"쇼운프로브",
        "city":"Goyang, Gyeonggi-do (KINTEX area)",
        "contact_name":"","title":"",
        "email":"info@shownprove.co.kr","phone_whatsapp":"+82 70 0054-1712",
        "website":"https://www.shownprove.co.kr",
        "business":"Indoor & outdoor LED screens; events & fixed installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":101,"country":"Korea","region":"Asia",
        "company_en":"AVAVISION","company_local":"아바비전",
        "city":"Anyang, Gyeonggi-do",
        "contact_name":"박재준 (Park Jae-Jun)","title":"CEO",
        "email":"sales@avavision.co.kr","phone_whatsapp":"+82 31 443-3311",
        "website":"https://www.avavision.co.kr",
        "business":"Commercial LED screen integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":102,"country":"Korea","region":"Asia",
        "company_en":"KOSES","company_local":"코세스",
        "city":"Guri, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"mara107@naver.com","phone_whatsapp":"+82 2 470-1156",
        "website":"https://coses.co.kr",
        "business":"Outdoor LED screen (since 2004)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":103,"country":"Korea","region":"Asia",
        "company_en":"ILLIES","company_local":"일리스",
        "city":"Seoul (Yongsan-gu)",
        "contact_name":"","title":"",
        "email":"illis@illis.co.kr","phone_whatsapp":"+82 2 971-1215",
        "website":"https://illis.co.kr",
        "business":"Indoor/fixed LED screen solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":104,"country":"Korea","region":"Asia",
        "company_en":"Daesung LED","company_local":"대성LED",
        "city":"Gwangmyeong, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"ygh5680@naver.com","phone_whatsapp":"+82 1544-9647",
        "website":"https://daesungled.com",
        "business":"Commercial LED screen",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":105,"country":"Korea","region":"Asia",
        "company_en":"Basic Tech","company_local":"베이직테크",
        "city":"Paju, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"basic@basictech.co.kr","phone_whatsapp":"+82 70 7004-2200",
        "website":"https://basictech.co.kr",
        "business":"Commercial LED display (since 1996)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":106,"country":"Korea","region":"Asia",
        "company_en":"Shinwoo SNC","company_local":"신우에스앤씨",
        "city":"Seoul (Geumcheon-gu)",
        "contact_name":"임 권 (Lim Kwon)","title":"CEO",
        "email":"webmaster@shinwoosnc.com","phone_whatsapp":"+82 2 701-2787",
        "website":"https://swsled.co.kr",
        "business":"Indoor/outdoor LED; rental LED; 20+ service centers nationwide",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":107,"country":"Korea","region":"Asia",
        "company_en":"Neulsom LED","company_local":"늘솜LED",
        "city":"Siheung, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 31 487-7812",
        "website":"https://www.nsled.kr",
        "business":"Rental LED screen specialist",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":108,"country":"Korea","region":"Asia",
        "company_en":"Winmeditech","company_local":"윈미디텍",
        "city":"Seoul (Yeongdeungpo-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 3272-3939",
        "website":"https://winmedi.co.kr",
        "business":"Commercial LED display, AV integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":109,"country":"Korea","region":"Asia",
        "company_en":"Primemedia Korea","company_local":"프라임미디어",
        "city":"Goyang, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 754-0004",
        "website":"https://www.primemedia.co.kr",
        "business":"Rental LED screen; events & corporate",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":110,"country":"Korea","region":"Asia",
        "company_en":"TAG Solution","company_local":"TAG솔루션",
        "city":"Seoul (Gwanak-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 10 3062-1050",
        "website":"https://tagsolution.kr",
        "business":"Transparent & rental LED screens",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":111,"country":"Korea","region":"Asia",
        "company_en":"Mpartners","company_local":"엠파트너스",
        "city":"Seoul (Yeongdeungpo-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 3281-9660",
        "website":"https://mpartners.co.kr",
        "business":"Commercial LED display distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":112,"country":"Korea","region":"Asia",
        "company_en":"RAON VISUAL","company_local":"라온비주얼",
        "city":"Seoul (Seongdong-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 2088-7626",
        "website":"https://www.raonvisual.co.kr",
        "business":"Commercial LED screen integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":113,"country":"Korea","region":"Asia",
        "company_en":"ADEG Korea","company_local":"에이덱",
        "city":"Seoul (Yongsan-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 70 8866-8144",
        "website":"https://www.adeg.co.kr",
        "business":"Indoor/outdoor fixed LED screens",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":114,"country":"Korea","region":"Asia",
        "company_en":"VISSEM","company_local":"비쎔",
        "city":"Yongin, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 31 288-3428",
        "website":"https://www.vissem.com",
        "business":"Outdoor LED screen",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":115,"country":"Korea","region":"Asia",
        "company_en":"Kiosk Korea","company_local":"키오스크코리아",
        "city":"Seoul (Geumcheon-gu)",
        "contact_name":"","title":"",
        "email":"help@kioskkorea.kr","phone_whatsapp":"+82 70 8623-1525",
        "website":"https://kioskkorea.com",
        "business":"LED kiosk & digital signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":116,"country":"Korea","region":"Asia",
        "company_en":"D-King LED","company_local":"디킹LED",
        "city":"Seoul",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"https://dkingdisplay.com",
        "business":"XR LED / naked-eye 3D / stage rental LED / digital signage (20 years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":117,"country":"Korea","region":"Asia",
        "company_en":"JBDISPLAY","company_local":"JB디스플레이",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"https://www.jbdisplay.co.kr",
        "business":"LED display + digital signage; planning/R&D/mfg/installation (30+ years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Korean companies (with CEO info) ---
    {
        "no":118,"country":"Korea","region":"Asia",
        "company_en":"Shinelight","company_local":"주식회사 샤인라이트",
        "city":"Asan, Chungcheongnam-do / Suwon, Gyeonggi-do",
        "contact_name":"김현진 (Kim Hyun-jin)","title":"CEO",
        "email":"led@shinelight.kr","phone_whatsapp":"+82 1666-1548",
        "website":"https://shinelight.kr",
        "business":"Indoor/outdoor LED display; transparent screen; media facade",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":119,"country":"Korea","region":"Asia",
        "company_en":"SYSMATE","company_local":"주식회사 시스메이트",
        "city":"Seoul (Geumcheon-gu)",
        "contact_name":"정종균 (Jung Jong-gyun)","title":"CEO",
        "email":"sysmate@sysmate.co.kr","phone_whatsapp":"+82 1833-9009",
        "website":"https://sysmate.co.kr",
        "business":"LED display system integration & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":120,"country":"Korea","region":"Asia",
        "company_en":"Koled","company_local":"주식회사 코레드",
        "city":"Ansan, Gyeonggi-do",
        "contact_name":"이영훈 (Lee Young-hoon)","title":"CEO",
        "email":"","phone_whatsapp":"+82 31 478-5330 / 010-6791-7212",
        "website":"https://koled.co.kr",
        "business":"LED display wholesale & distribution",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":121,"country":"Korea","region":"Asia",
        "company_en":"Asolcompany","company_local":"아솔컴퍼니",
        "city":"Seoul (Dongdaemun-gu)",
        "contact_name":"정경식 (Jeong Gyeong-sik)","title":"CEO",
        "email":"itsolu@naver.com","phone_whatsapp":"+82 2 1544-7581",
        "website":"",
        "business":"LED display installation & integration",
        "facebook":"","instagram":"","linkedin":"",
    },
]

# ─── Workbook ─────────────────────────────────────────────────────────────────
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "LED Leads - All Markets"

COLOR_HEADER_BG   = "1F4E79"
COLOR_HEADER_FONT = "FFFFFF"

COUNTRY_COLORS = {
    "Brazil":    "D9EAD3",
    "Colombia":  "FCE5CD",
    "Chile":     "D0E4F5",
    "Peru":      "FFF2CC",
    "Argentina": "EAD1DC",
    "USA":       "CFE2F3",
    "Canada":    "E6D0DE",
    "Mexico":    "D9D2E9",
    "Korea":     "F4CCCC",
}

headers = [
    "No.", "Region", "Country", "City",
    "Company (English)", "Company (Local Language)",
    "Contact Person", "Title",
    "Email", "Phone / WhatsApp / Kakao",
    "Website", "Main Business",
    "Facebook", "Instagram", "LinkedIn",
    "Notes / Action",
]

thin = Side(style="thin", color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

hfill  = PatternFill("solid", fgColor=COLOR_HEADER_BG)
hfont  = Font(bold=True, color=COLOR_HEADER_FONT, size=11)
halign = Alignment(horizontal="center", vertical="center", wrap_text=True)

for ci, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=ci, value=h)
    cell.fill = hfill; cell.font = hfont
    cell.alignment = halign; cell.border = border
ws.row_dimensions[1].height = 36

for ri, lead in enumerate(leads, 2):
    row_data = [
        lead["no"], lead["region"], lead["country"], lead["city"],
        lead["company_en"], lead["company_local"],
        lead["contact_name"], lead["title"],
        lead["email"], lead["phone_whatsapp"],
        lead["website"], lead["business"],
        lead["facebook"], lead["instagram"], lead["linkedin"],
        "",  # Notes
    ]
    rfill = PatternFill("solid", fgColor=COUNTRY_COLORS.get(lead["country"], "FFFFFF"))
    for ci, val in enumerate(row_data, 1):
        cell = ws.cell(row=ri, column=ci, value=val)
        cell.fill = rfill
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        cell.border = border
    ws.row_dimensions[ri].height = 26

col_widths = [5, 14, 12, 25, 28, 28, 18, 14, 32, 32, 34, 50, 32, 30, 42, 20]
for ci, w in enumerate(col_widths, 1):
    ws.column_dimensions[get_column_letter(ci)].width = w
ws.freeze_panes = "A2"

# ─── Summary sheet ────────────────────────────────────────────────────────────
ws2 = wb.create_sheet("Summary")
ws2["A1"] = "LED Display Leads — Americas + Korea  (v3)"
ws2["A1"].font = Font(bold=True, size=14, color=COLOR_HEADER_BG)

ws2["A3"] = "Region"; ws2["B3"] = "Country"; ws2["C3"] = "# Companies"
for cell in ws2["A3:C3"][0]:
    cell.fill = hfill; cell.font = hfont
    cell.alignment = Alignment(horizontal="center")

from collections import Counter
country_count = Counter(lead["country"] for lead in leads)

summary = [
    ("South America", "Brazil",    country_count["Brazil"]),
    ("South America", "Colombia",  country_count["Colombia"]),
    ("South America", "Chile",     country_count["Chile"]),
    ("South America", "Peru",      country_count["Peru"]),
    ("South America", "Argentina", country_count["Argentina"]),
    ("North America", "USA",       country_count["USA"]),
    ("North America", "Canada",    country_count["Canada"]),
    ("North America", "Mexico",    country_count["Mexico"]),
    ("Asia",          "Korea",     country_count["Korea"]),
]
for i, (region, country, cnt) in enumerate(summary, 4):
    ws2.cell(row=i, column=1, value=region)
    ws2.cell(row=i, column=2, value=country)
    ws2.cell(row=i, column=3, value=cnt)
    f = PatternFill("solid", fgColor=COUNTRY_COLORS.get(country, "FFFFFF"))
    for c in range(1, 4):
        ws2.cell(row=i, column=c).fill = f

total_row = len(summary) + 4
ws2.cell(row=total_row, column=1, value="TOTAL")
ws2.cell(row=total_row, column=3, value=sum(r[2] for r in summary))
for c in range(1, 4):
    ws2.cell(row=total_row, column=c).font = Font(bold=True)

for col in ["A","B","C"]:
    ws2.column_dimensions[col].width = 22

# ─── Tips sheet ───────────────────────────────────────────────────────────────
ws3 = wb.create_sheet("开发建议")
tips = [
    ("优先级", "建议"),
    ("★★★ 立即联系", "WhatsApp直接发开发消息（南美市场首选渠道）"),
    ("★★★ 立即联系", "有邮箱的公司发英语+当地语言双语开发信"),
    ("★★ 深挖联系人", "通过LinkedIn搜索公司的采购/老板职位 (Gerente/Compras/Procurement)"),
    ("★★ 社媒触达", "INS/Facebook发DM，附产品图+报价意向"),
    ("★ 后续跟进", "韩国公司建议英文邮件 + 附韩文简介，有CEO姓名直接点名联系"),
    ("注意", "South America: WhatsApp是主战场，不要只发邮件"),
    ("注意", "巴西公司联系语言优先葡萄牙语，其他南美优先西班牙语"),
    ("注意", "韩国公司多为中端集成商/安装商，适合推广中等价位产品"),
    ("注意", "Korea: 有CEO名字的公司优先联系，直接写 Dear Mr./Ms. XXX"),
]
ws3["A1"] = "客户开发执行建议"
ws3["A1"].font = Font(bold=True, size=13, color=COLOR_HEADER_BG)
ws3.merge_cells("A1:B1")
for i, (priority, tip) in enumerate(tips, 3):
    ws3.cell(row=i, column=1, value=priority).font = Font(bold=(i==3))
    ws3.cell(row=i, column=2, value=tip)
ws3.column_dimensions["A"].width = 20
ws3.column_dimensions["B"].width = 60

out = r"C:\Users\Administrator\ai-topic-generator\output\leads\LED_Display_Leads_v3.xlsx"
wb.save(out)
print(f"Saved: {out}")
print(f"Total records: {len(leads)}")
for region, country, cnt in summary:
    print(f"  {country}: {cnt}")
