"""LED Display Leads - Americas + Korea - Full Version v4
Updates from v3:
  - +8 new Brazil companies
  - +19 new Chile companies
  - +9 new Peru companies
  - +14 new Argentina companies
  - +9 new Mexico companies
  - +29 new Korea companies (incl. Busan cluster, Daegu, Incheon)
  - Fixed ADEG Korea email
  Total: ~209 records
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from collections import Counter

leads = [
    # ==================== BRAZIL (25 → 33) ====================
    {
        "no":1,"country":"Brazil","region":"South America",
        "company_en":"LedWave","company_local":"LedWave",
        "city":"São Paulo / Goiânia / Rio / Brasília",
        "contact_name":"","title":"",
        "email":"contato@ledwave.com.br",
        "phone_whatsapp":"+55 11 3044-4609 / 0800 943-7800",
        "website":"http://www.ledwave.com.br",
        "business":"LED panel sales, rental, OOH media; B Corp certified",
        "facebook": "ledwavesaopaulo","instagram": "ledwave","linkedin":"linkedin.com/company/ledwave",
    },
    {
        "no":2,"country":"Brazil","region":"South America",
        "company_en":"Crialed Visual Productions","company_local":"Crialed Produções Visuais e Eventos",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@crialed.com.br",
        "phone_whatsapp":"+55 11 2291-0031 / WA: +55 11 95663-5316",
        "website":"https://www.crialed.com.br",
        "business":"LED panel sales, rental & events (since 2008)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":3,"country":"Brazil","region":"South America",
        "company_en":"LED 10","company_local":"LED 10",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@led10.com.br",
        "phone_whatsapp":"+55 11 2115-3091",
        "website":"http://led10.com.br",
        "business":"LED panel sales & rental (since 2010)",
        "facebook": "paineisled10","instagram":"","linkedin":"",
    },
    {
        "no":4,"country":"Brazil","region":"South America",
        "company_en":"P1LED / Prime LED","company_local":"P1LED / Prime Led",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@p1led.com.br",
        "phone_whatsapp":"+55 11 2626-2460 / WA: +55 11 99137-8503",
        "website":"https://www.primeled.com.br",
        "business":"LED panel pioneer, retail + commercial, 15+ years; reseller program",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":5,"country":"Brazil","region":"South America",
        "company_en":"The LED","company_local":"The LED",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"comercial@theled.com.br",
        "phone_whatsapp":"+55 11 98940-4332 / +55 11 96334-5500",
        "website":"http://www.theled.com.br",
        "business":"Largest LED visual communications company in Brazil; distributor network",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":6,"country":"Brazil","region":"South America",
        "company_en":"Dshow","company_local":"Dshow",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"dshow@dshow.com.br",
        "phone_whatsapp":"+55 11 99714-4969 / +55 11 3392-1514",
        "website":"http://www.dshow.com.br",
        "business":"Indoor/outdoor/flexible LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":7,"country":"Brazil","region":"South America",
        "company_en":"NA Equipment","company_local":"N.A. Equipamentos",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"orcamentos1@naequipamentos.com.br",
        "phone_whatsapp":"+55 11 3606-7878",
        "website":"http://www.naequipamentos.com.br",
        "business":"Full-color LED panels + professional video equipment",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":8,"country":"Brazil","region":"South America",
        "company_en":"Nationstar Brasil","company_local":"Nationstar Brasil",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"vendas@nationstar.com.br",
        "phone_whatsapp":"+55 11 58974392",
        "website":"https://www.nationstarbrasil.com.br",
        "business":"Full-color LED panel supplier",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":9,"country":"Brazil","region":"South America",
        "company_en":"Optiart","company_local":"Optiart",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"comercial@optiart.com.br",
        "phone_whatsapp":"+55 11 5060-4140",
        "website":"https://optiart.com.br",
        "business":"Retail digital signage & LED; official Samsung distributor in Brazil",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":10,"country":"Brazil","region":"South America",
        "company_en":"Elite LED","company_local":"Elite LED",
        "city":"Rio de Janeiro, RJ",
        "contact_name":"","title":"",
        "email":"contato@eliteled.com.br",
        "phone_whatsapp":"+55 21 3344-0206",
        "website":"https://eliteled.com.br",
        "business":"Exclusive distributor for PROMARC LED screens in Brazil",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":11,"country":"Brazil","region":"South America",
        "company_en":"Mundo de LED","company_local":"Mundo de LED",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"sales@mundodeled.com.br",
        "phone_whatsapp":"(88) 99605-3355",
        "website":"https://www.mundodeled.com.br",
        "business":"LED display sales & distribution (since 2013)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":12,"country":"Brazil","region":"South America",
        "company_en":"Innovate Brazil","company_local":"Innovate Brasil",
        "city":"Guarapari, ES",
        "contact_name":"","title":"",
        "email":"contato@innovatebrazil.com.br",
        "phone_whatsapp":"+55 27 3362-1614",
        "website":"https://innovatebrazil.com.br",
        "business":"LED panel manufacturer & retailer, 3-yr warranty, national delivery",
        "facebook":"","instagram": "innovatebrazil","linkedin":"",
    },
    {
        "no":13,"country":"Brazil","region":"South America",
        "company_en":"IDEA LED Panels","company_local":"IDEA Painéis de LED",
        "city":"Caxias do Sul, RS",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"(54) 3025-2921 / WA: wa.link/7jz8hw",
        "website":"https://www.paineldeled.com",
        "business":"LED panel supplier, 20 years, premium quality, B2B reseller-focused",
        "facebook": "ideapaineisdeled","instagram": "ideapaineisdeled","linkedin":"",
    },
    {
        "no":14,"country":"Brazil","region":"South America",
        "company_en":"NN LED","company_local":"NN LED",
        "city":"Campinas, SP",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"WA: (19) 99762-6990",
        "website":"",
        "business":"LED panel (P4) rental & LED robot; events",
        "facebook": "nnled","instagram":"","linkedin":"",
    },
    {
        "no":15,"country":"Brazil","region":"South America",
        "company_en":"Power LED","company_local":"Power Led",
        "city":"Campinas, SP",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"(19) 3365-1636 / WA: (19) 99901-2883",
        "website":"",
        "business":"LED panel sales & rental",
        "facebook": "powerproled","instagram":"","linkedin":"",
    },
    {
        "no":16,"country":"Brazil","region":"South America",
        "company_en":"Rangel Panels","company_local":"Rangel Painéis",
        "city":"São Paulo, SP",
        "contact_name":"Flávio","title":"Owner",
        "email":"flavio@rangelpaineis.com.br",
        "phone_whatsapp":"+55 11 99995-6612",
        "website":"https://rangelpaineis.com.br",
        "business":"LED display & advertising panels (since 1998)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":17,"country":"Brazil","region":"South America",
        "company_en":"Trend LED","company_local":"Trend Led",
        "city":"Brasília, DF",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED panel rental & sales",
        "facebook": "Trendbsb","instagram":"","linkedin":"",
    },
    {
        "no":18,"country":"Brazil","region":"South America",
        "company_en":"Rogustec","company_local":"Rogustec",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"atendimento@rogustec.com.br",
        "phone_whatsapp":"+55 11 5525-1399",
        "website":"https://rogustec.com.br",
        "business":"LED display & digital signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":19,"country":"Brazil","region":"South America",
        "company_en":"Aloc LED","company_local":"Aloc",
        "city":"Belo Horizonte, MG",
        "contact_name":"","title":"",
        "email":"belohorizonte@aloc.com.br",
        "phone_whatsapp":"(31) 3058-0600",
        "website":"https://aloc.com.br",
        "business":"LED display & professional AV equipment",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":20,"country":"Brazil","region":"South America",
        "company_en":"TOPLED Multimidia","company_local":"TOPLED",
        "city":"Goiânia, GO",
        "contact_name":"","title":"",
        "email":"contato@topledmultimidia.com.br",
        "phone_whatsapp":"(62) 3099-3817",
        "website":"https://topledmultimidia.com.br",
        "business":"LED multimedia panel sales & rental (Goiânia region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":21,"country":"Brazil","region":"South America",
        "company_en":"LATINLED","company_local":"LATINLED",
        "city":"Florianópolis, SC",
        "contact_name":"","title":"",
        "email":"info@latinled.com.br",
        "phone_whatsapp":"+55 48 9115-2071",
        "website":"https://latinled.com.br",
        "business":"LED display wholesale & distribution",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":22,"country":"Brazil","region":"South America",
        "company_en":"PLL Painéis","company_local":"PLL Painéis",
        "city":"Brazil",
        "contact_name":"Carlos","title":"Sales",
        "email":"carlos@pllpaineis.com.br",
        "phone_whatsapp":"",
        "website":"",
        "business":"LED panel distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":23,"country":"Brazil","region":"South America",
        "company_en":"All Trading","company_local":"All Trading",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"comercial@alltrading.com.br",
        "phone_whatsapp":"(11) 98477-0223",
        "website":"",
        "business":"LED display trading & import",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":24,"country":"Brazil","region":"South America",
        "company_en":"Qualipix Video Wall","company_local":"Video Wall BH / Qualipix",
        "city":"Belo Horizonte, MG",
        "contact_name":"","title":"",
        "email":"contato@qualipix.com.br",
        "phone_whatsapp":"(31) 3568-6835",
        "website":"",
        "business":"LED video wall installation & sales",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":25,"country":"Brazil","region":"South America",
        "company_en":"Pantallas Brasil LED","company_local":"Pantallas Brasil LED",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"contato@pantallasbrasil.com.br",
        "phone_whatsapp":"+55 11 97640-6060",
        "website":"https://pantallasbrasil.com.br",
        "business":"LED screen distributor, indoor/outdoor advertising",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Brazil companies (v4) ---
    {
        "no":26,"country":"Brazil","region":"South America",
        "company_en":"Grecko LED","company_local":"Grecko LED",
        "city":"Brazil",
        "contact_name":"","title":"",
        "email":"info@greckoled.com",
        "phone_whatsapp":"",
        "website":"https://greckoled.com",
        "business":"LED display sales & integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":27,"country":"Brazil","region":"South America",
        "company_en":"On Projecoes","company_local":"On Projeções",
        "city":"Brazil",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"",
        "website":"",
        "business":"LED display & projection solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":28,"country":"Brazil","region":"South America",
        "company_en":"Vital Tech","company_local":"Vital Tech",
        "city":"Campinas, SP",
        "contact_name":"","title":"",
        "email":"contato@vitaltech.com.br",
        "phone_whatsapp":"",
        "website":"https://vitaltech.com.br",
        "business":"LED display solutions & AV technology",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":29,"country":"Brazil","region":"South America",
        "company_en":"Leyard Brasil","company_local":"Leyard Brasil",
        "city":"São Paulo, SP",
        "contact_name":"","title":"",
        "email":"sales.brazil@leyardgroup.com",
        "phone_whatsapp":"",
        "website":"https://leyard.com/br",
        "business":"Fine-pitch LED display & video wall (global brand, Brazil branch)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":30,"country":"Brazil","region":"South America",
        "company_en":"Grupo Pleno","company_local":"Grupo Pleno",
        "city":"Brazil",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"",
        "website":"",
        "business":"LED display solutions group",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":31,"country":"Brazil","region":"South America",
        "company_en":"LED ABC","company_local":"LED ABC",
        "city":"Santo André, SP",
        "contact_name":"","title":"",
        "email":"vendas@ledabc.com.br",
        "phone_whatsapp":"",
        "website":"https://ledabc.com.br",
        "business":"LED display sales & installation (ABC region São Paulo)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":32,"country":"Brazil","region":"South America",
        "company_en":"Ashow Imagem","company_local":"Ashow Imagem",
        "city":"Brazil",
        "contact_name":"","title":"",
        "email":"",
        "phone_whatsapp":"",
        "website":"",
        "business":"LED display & events imaging solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":33,"country":"Brazil","region":"South America",
        "company_en":"CLICK LED","company_local":"CLICK LED",
        "city":"Brazil",
        "contact_name":"","title":"",
        "email":"contato@clickled.com.br",
        "phone_whatsapp":"",
        "website":"https://clickled.com.br",
        "business":"LED display sales & digital signage",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== COLOMBIA (5) ====================
    {
        "no":34,"country":"Colombia","region":"South America",
        "company_en":"PubliMaster Colombia","company_local":"Publi Master SJ",
        "city":"Medellín",
        "contact_name":"","title":"",
        "email":"ventas@publimastercolombia.com",
        "phone_whatsapp":"+57 311 2419363",
        "website":"https://publimastercolombia.com",
        "business":"LED screen importer & commercializer; events/indoor/outdoor advertising",
        "facebook": "publimasterSJ","instagram": "publimastersj","linkedin":"",
    },
    {
        "no":35,"country":"Colombia","region":"South America",
        "company_en":"Digital Signage Colombia","company_local":"Digital Signage Colombia SAS",
        "city":"Bogotá",
        "contact_name":"","title":"",
        "email":"negocios@dscolombia.co",
        "phone_whatsapp":"601 4321929 / WA: +57 317 521 1104",
        "website":"https://dscolombia.co",
        "business":"Official Samsung distributor (Colombia); LED video wall, touch screens; 15+ yrs",
        "facebook": "DigitalSignageColombia","instagram": "digitalsignagecolombia","linkedin":"linkedin.com/company/digital-signage-colombia-sas",
    },
    {
        "no":36,"country":"Colombia","region":"South America",
        "company_en":"MachineTronics","company_local":"MachineTronics",
        "city":"Bogotá / Medellín / Cali",
        "contact_name":"Yulieth Cruz","title":"",
        "email":"","phone_whatsapp":"+57 318 3400796 / +57 316 4086143",
        "website":"https://www.machinetronics.com",
        "business":"LED screen manufacturer & distributor; advertising/events/real estate/corporate",
        "facebook": "MachineTronics","instagram":"","linkedin":"linkedin.com/in/yulieth-cruz-145a784a",
    },
    {
        "no":37,"country":"Colombia","region":"South America",
        "company_en":"InOut Soluciones","company_local":"InOut Soluciones",
        "city":"Bogotá",
        "contact_name":"","title":"",
        "email":"info@inoutsoluciones.com",
        "phone_whatsapp":"+57 312 356 9648",
        "website":"https://www.inoutsoluciones.com",
        "business":"LED wall manufacturer; indoor/outdoor; offices/malls/education; 15+ yrs",
        "facebook":"","instagram": "inoutsoluciones","linkedin":"linkedin.com/company/inout-soluciones",
    },
    {
        "no":38,"country":"Colombia","region":"South America",
        "company_en":"Visual Led Colombia","company_local":"Visual Led Colombia",
        "city":"Colombia",
        "contact_name":"","title":"",
        "email":"ventas@visualled.com","phone_whatsapp":"",
        "website":"https://visualled.com",
        "business":"LED screen design & manufacturing for indoor/outdoor advertising (since 2003)",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== CHILE (9 → 28) ====================
    {
        "no":39,"country":"Chile","region":"South America",
        "company_en":"PLED Chile","company_local":"PLED.cl",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@pled.cl","phone_whatsapp":"+56 9 3659-1068",
        "website":"https://www.pled.cl",
        "business":"LED display sales & rental",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":40,"country":"Chile","region":"South America",
        "company_en":"Tecnogroup Chile","company_local":"Tecnogroup",
        "city":"Las Condes, Santiago",
        "contact_name":"","title":"",
        "email":"contacto@tecnogroup.cl","phone_whatsapp":"+56 9 5449-1032",
        "website":"https://tecnogroup.cl",
        "business":"LED display & tech solutions; retail nationwide",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":41,"country":"Chile","region":"South America",
        "company_en":"Led Neon Chile","company_local":"Led Neon Chile (LNC)",
        "city":"Renca, Santiago",
        "contact_name":"","title":"",
        "email":"ventas@lnc.cl","phone_whatsapp":"+56 2 2957-4444",
        "website":"https://www.lnc.cl",
        "business":"LED display & neon, 30 years experience; electronic displays",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":42,"country":"Chile","region":"South America",
        "company_en":"Remote Media","company_local":"Remote Media",
        "city":"Ñuñoa, Santiago",
        "contact_name":"","title":"",
        "email":"info@remotemedia.cl","phone_whatsapp":"+56 2 2352-5532",
        "website":"https://remotemedia.cl",
        "business":"Digital signage & LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":43,"country":"Chile","region":"South America",
        "company_en":"Fullvision","company_local":"Fullvision",
        "city":"Ñuñoa, Santiago",
        "contact_name":"","title":"",
        "email":"info@fullvision.cl","phone_whatsapp":"+56 2 2455-6596",
        "website":"https://www.fullvision.cl",
        "business":"LED display system integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":44,"country":"Chile","region":"South America",
        "company_en":"Demco Ltda","company_local":"Demco Ltda",
        "city":"Quilicura, Santiago",
        "contact_name":"","title":"",
        "email":"info@demco.cl","phone_whatsapp":"+56 2 2782-1800",
        "website":"https://www.demco.cl",
        "business":"Wholesale distributor (since 1983); LED/AV products",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":45,"country":"Chile","region":"South America",
        "company_en":"4D LED Screens","company_local":"4D Pantallas LEAD",
        "city":"Las Condes, Santiago",
        "contact_name":"","title":"",
        "email":"info@cuatrod.net","phone_whatsapp":"+56 2 434-1800",
        "website":"https://www.cuatrod.net",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":46,"country":"Chile","region":"South America",
        "company_en":"VideoWall Corporation","company_local":"VideoWall Corporation SPA",
        "city":"La Reina, Santiago",
        "contact_name":"","title":"",
        "email":"info@videowall.cl","phone_whatsapp":"+56 9 8808-3220",
        "website":"https://www.videowall.cl",
        "business":"LED video wall systems integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":47,"country":"Chile","region":"South America",
        "company_en":"Cleverox","company_local":"Cleverox",
        "city":"Huechuraba, Santiago",
        "contact_name":"","title":"",
        "email":"contacto@cleverox.com","phone_whatsapp":"+56 2 2956-3200",
        "website":"https://www.cleverox.com",
        "business":"LED display & AV integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Chile companies (v4) ---
    {
        "no":48,"country":"Chile","region":"South America",
        "company_en":"DECIBELPIXEL","company_local":"DECIBELPIXEL",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@decibelpixel.cl","phone_whatsapp":"",
        "website":"https://decibelpixel.cl",
        "business":"LED display & digital signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":49,"country":"Chile","region":"South America",
        "company_en":"VoxLine","company_local":"VoxLine",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@voxline.cl","phone_whatsapp":"",
        "website":"https://voxline.cl",
        "business":"LED screen sales & AV solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":50,"country":"Chile","region":"South America",
        "company_en":"Lumed Ads","company_local":"Lumed Ads",
        "city":"Santiago",
        "contact_name":"Joselyn Villanueva","title":"",
        "email":"joselyn.villanueva@lumedads.cl","phone_whatsapp":"",
        "website":"https://lumedads.cl",
        "business":"Outdoor LED advertising & DOOH media",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":51,"country":"Chile","region":"South America",
        "company_en":"VisualCom","company_local":"VisualCom",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@visualcom.cl","phone_whatsapp":"",
        "website":"https://visualcom.cl",
        "business":"LED display & visual communication systems",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":52,"country":"Chile","region":"South America",
        "company_en":"ECGROUP","company_local":"ECGROUP",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@ecgroup.cl","phone_whatsapp":"",
        "website":"https://ecgroup.cl",
        "business":"LED display & AV system integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":53,"country":"Chile","region":"South America",
        "company_en":"Mantencion LED","company_local":"Mantencion LED",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen maintenance & repair services",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":54,"country":"Chile","region":"South America",
        "company_en":"PubliLed Tarapacá","company_local":"PubliLed Tarapacá",
        "city":"Iquique, Tarapacá",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED outdoor advertising (northern Chile)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":55,"country":"Chile","region":"South America",
        "company_en":"full-LED","company_local":"full-LED",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"Full-range LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":56,"country":"Chile","region":"South America",
        "company_en":"Nitroled","company_local":"Nitroled",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@nitroled.cl","phone_whatsapp":"",
        "website":"https://nitroled.cl",
        "business":"LED display sales & digital signage",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":57,"country":"Chile","region":"South America",
        "company_en":"Mathieu Producciones","company_local":"Mathieu Producciones",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen rental & event production",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":58,"country":"Chile","region":"South America",
        "company_en":"Global Vía Pública","company_local":"Global Vía Pública",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"Outdoor LED billboard & digital OOH media",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":59,"country":"Chile","region":"South America",
        "company_en":"Estem Chile","company_local":"Estem Chile",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@estem.cl","phone_whatsapp":"",
        "website":"https://estem.cl",
        "business":"LED display & electronic signage",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":60,"country":"Chile","region":"South America",
        "company_en":"Vwalls.cl","company_local":"Vwalls",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@vwalls.cl","phone_whatsapp":"",
        "website":"https://vwalls.cl",
        "business":"LED video wall solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":61,"country":"Chile","region":"South America",
        "company_en":"LEDMUNDO","company_local":"LEDMUNDO",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"contacto@ledmundo.cl","phone_whatsapp":"",
        "website":"https://ledmundo.cl",
        "business":"LED display sales & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":62,"country":"Chile","region":"South America",
        "company_en":"Elink Digital","company_local":"Elink Digital",
        "city":"Concepción",
        "contact_name":"","title":"",
        "email":"info@elink.cl","phone_whatsapp":"",
        "website":"https://elink.cl",
        "business":"Digital LED display & signage (Concepción region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":63,"country":"Chile","region":"South America",
        "company_en":"FBAudio","company_local":"FBAudio",
        "city":"Valparaíso",
        "contact_name":"","title":"",
        "email":"contacto@fbaudio.cl","phone_whatsapp":"",
        "website":"https://fbaudio.cl",
        "business":"LED screen & audio-visual solutions (Valparaíso)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":64,"country":"Chile","region":"South America",
        "company_en":"VMedios","company_local":"VMedios",
        "city":"Valparaíso",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED advertising media solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":65,"country":"Chile","region":"South America",
        "company_en":"Integracion Digital SpA","company_local":"Integración Digital SpA",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"info@integraciondigital.cl","phone_whatsapp":"",
        "website":"https://integraciondigital.cl",
        "business":"LED & digital signage system integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":66,"country":"Chile","region":"South America",
        "company_en":"FABRICA CREATIVA","company_local":"Fábrica Creativa",
        "city":"Santiago",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display & creative visual production",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== PERU (10 → 19) ====================
    {
        "no":67,"country":"Peru","region":"South America",
        "company_en":"EXCTECLED Peru","company_local":"Pantallas LED Peru - EXCTECLED",
        "city":"San Isidro, Lima",
        "contact_name":"","title":"",
        "email":"ventas@exctecled.com","phone_whatsapp":"+51 913059191",
        "website":"https://exctecled.com",
        "business":"Leading LED advertising screen distributor in Peru; fixed/rental/stadium",
        "facebook": "exctecled","instagram": "pantallasledperu","linkedin":"",
    },
    {
        "no":68,"country":"Peru","region":"South America",
        "company_en":"LED Laser Peru","company_local":"LED y Laser Peru",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@ledylaserperu.com","phone_whatsapp":"+51 933 488 195",
        "website":"https://ledylaserperu.com",
        "business":"LED display sales & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":69,"country":"Peru","region":"South America",
        "company_en":"BiG LED Peru","company_local":"BiG LED",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@bigledperu.com","phone_whatsapp":"+51 944 570 337",
        "website":"https://www.bigledperu.com",
        "business":"LED display wholesale & retail",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":70,"country":"Peru","region":"South America",
        "company_en":"Layset Peru","company_local":"Layset",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@layset2.com","phone_whatsapp":"+51 999 518 109",
        "website":"https://www.layset2.com",
        "business":"LED screen distributor, 15+ years",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":71,"country":"Peru","region":"South America",
        "company_en":"Orion Enterprises Peru","company_local":"ORION ENTERPRISES",
        "city":"Miraflores, Lima",
        "contact_name":"","title":"",
        "email":"info@orion-peru.com","phone_whatsapp":"+51 989 153 655",
        "website":"https://orion-peru.com",
        "business":"LED display solutions & integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":72,"country":"Peru","region":"South America",
        "company_en":"NeoLED Peru","company_local":"NEOLEDPERU",
        "city":"Los Olivos, Lima",
        "contact_name":"","title":"",
        "email":"info@neoledperu.com","phone_whatsapp":"+51 43 221 254",
        "website":"https://www.neoledperu.com",
        "business":"LED display sales & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":73,"country":"Peru","region":"South America",
        "company_en":"LED Maker Peru","company_local":"LED MAKER",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@ledmaker.com.pe","phone_whatsapp":"+51 967 645 520",
        "website":"https://ledmaker.com.pe",
        "business":"LED display manufacturer & supplier",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":74,"country":"Peru","region":"South America",
        "company_en":"INNOVALED Peru","company_local":"INNOVALED",
        "city":"Surquillo, Lima",
        "contact_name":"","title":"",
        "email":"ventas@innovaled.pe","phone_whatsapp":"+51 986 534 469",
        "website":"https://www.innovaled.pe",
        "business":"LED display innovation & sales",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":75,"country":"Peru","region":"South America",
        "company_en":"Goled Peru","company_local":"Goled Peru",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@goledperu.com","phone_whatsapp":"+51 1 639-6589",
        "website":"http://goledperu.com",
        "business":"14 years professional LED display & solar installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":76,"country":"Peru","region":"South America",
        "company_en":"Lontec Peru","company_local":"Lontec",
        "city":"La Perla, Callao",
        "contact_name":"","title":"",
        "email":"ventas@lontecperu.com","phone_whatsapp":"+51 914 968 151",
        "website":"https://lontecperu.com",
        "business":"LED display distributor & installer",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Peru companies (v4) ---
    {
        "no":77,"country":"Peru","region":"South America",
        "company_en":"Pantallas LED Peru","company_local":"Pantallas LED Peru",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@pantallasledperu.com","phone_whatsapp":"",
        "website":"https://pantallasledperu.com",
        "business":"LED screen sales & advertising solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":78,"country":"Peru","region":"South America",
        "company_en":"SCRATCH Peru","company_local":"SCRATCH Peru",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"info@scratchperu.com","phone_whatsapp":"",
        "website":"https://scratchperu.com",
        "business":"LED display & digital media solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":79,"country":"Peru","region":"South America",
        "company_en":"Stringnet","company_local":"Stringnet",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"ventas@stringnet.pe","phone_whatsapp":"",
        "website":"https://stringnet.pe",
        "business":"LED display network & distribution",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":80,"country":"Peru","region":"South America",
        "company_en":"Sono Luz","company_local":"Sono Luz",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"info@sonoluz.com.pe","phone_whatsapp":"",
        "website":"https://sonoluz.com.pe",
        "business":"LED screen & audio-visual solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":81,"country":"Peru","region":"South America",
        "company_en":"4K Audiovisual Peru","company_local":"4K Audiovisual",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display & 4K AV solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":82,"country":"Peru","region":"South America",
        "company_en":"VISUA LED","company_local":"VISUA LED",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display sales & visual solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":83,"country":"Peru","region":"South America",
        "company_en":"GrupoAudia","company_local":"GrupoAudia",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen & audiovisual group",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":84,"country":"Peru","region":"South America",
        "company_en":"SMLED Peru","company_local":"SMLED",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":85,"country":"Peru","region":"South America",
        "company_en":"IMARKETING VISUAL 360","company_local":"IMARKETING VISUAL 360",
        "city":"Lima",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen & 360° visual marketing solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== ARGENTINA (10 → 24) ====================
    {
        "no":86,"country":"Argentina","region":"South America",
        "company_en":"Dinalight","company_local":"Dinalight",
        "city":"Buenos Aires (Franklin D. Roosevelt 3644)",
        "contact_name":"","title":"",
        "email":"info@dinalight.com",
        "phone_whatsapp":"+54 9 11 4064-9989 / WA: +54 9 11 3848-0840",
        "website":"https://www.dinalight.com",
        "business":"LED manufacturer 20+ yrs; indoor/outdoor/rental/mesh; expands across LatAm",
        "facebook": "p/Dinalightlatam-100072348303065","instagram": "dinalight.led","linkedin":"",
    },
    {
        "no":87,"country":"Argentina","region":"South America",
        "company_en":"Grupo UNO LED","company_local":"Grupo UNO LED",
        "city":"Martín Coronado, Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@grupounoled.com","phone_whatsapp":"+54 9 11 5740-6998",
        "website":"https://grupounoled.com",
        "business":"Argentine LED screen factory, 3000+ clients; outdoor/indoor/mobile + G1 Studio CMS",
        "facebook": "grupounoled","instagram": "grupounoled","linkedin":"",
    },
    {
        "no":88,"country":"Argentina","region":"South America",
        "company_en":"Multiled","company_local":"Multiled",
        "city":"Buenos Aires (Salta 285)",
        "contact_name":"","title":"",
        "email":"info@multiled.com.ar","phone_whatsapp":"4373-9500",
        "website":"https://www.multiled.com.ar",
        "business":"Advertising LED screens, marketing panels, industrial",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":89,"country":"Argentina","region":"South America",
        "company_en":"Microled Argentina","company_local":"Microled Argentina",
        "city":"CABA (Pichincha 188)",
        "contact_name":"","title":"",
        "email":"info@microled.com.ar","phone_whatsapp":"+54 11 4954-0056",
        "website":"https://microled.com.ar",
        "business":"LED signage & display",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":90,"country":"Argentina","region":"South America",
        "company_en":"Tecnoled Argentina","company_local":"Tecnoled",
        "city":"Tigre, Buenos Aires",
        "contact_name":"","title":"",
        "email":"ventas@tecnoled.ar","phone_whatsapp":"+54 9 11 6488-4200",
        "website":"https://tecnoled.ar",
        "business":"LED screens, digital signage, visual solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":91,"country":"Argentina","region":"South America",
        "company_en":"Grafica LED","company_local":"Gráfica Led",
        "city":"Villa Martelli, Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@graficaled.com","phone_whatsapp":"+54 9 11 3524-9417",
        "website":"https://www.graficaled.com",
        "business":"LED screen rental & fixed installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":92,"country":"Argentina","region":"South America",
        "company_en":"Street LED Argentina","company_local":"Street Led Argentina",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@streetled.com.ar","phone_whatsapp":"+54 11 2187-9006",
        "website":"https://streetled.com.ar",
        "business":"Indoor/outdoor LED screens",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":93,"country":"Argentina","region":"South America",
        "company_en":"Led HD Argentina","company_local":"Led HD",
        "city":"Lomas de Zamora, Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@ledhd.com.ar","phone_whatsapp":"+54 11 2356-3301",
        "website":"https://ledhd.com.ar",
        "business":"HD LED screens, active displays",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":94,"country":"Argentina","region":"South America",
        "company_en":"VDS Argentina","company_local":"VDS",
        "city":"CABA",
        "contact_name":"","title":"",
        "email":"vds@vds.com.ar","phone_whatsapp":"+54 9 11 6094-3669",
        "website":"https://www.vds.com.ar",
        "business":"Rental LED screens & video walls",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":95,"country":"Argentina","region":"South America",
        "company_en":"Altavista LED","company_local":"Altavista LED",
        "city":"Córdoba",
        "contact_name":"","title":"",
        "email":"info@altavistaled.com","phone_whatsapp":"+54 351 254 5609",
        "website":"https://altavistaled.com",
        "business":"Advertising LED screens, DOOH advertising",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Argentina companies (v4) ---
    {
        "no":96,"country":"Argentina","region":"South America",
        "company_en":"Evolutionis","company_local":"Evolutionis",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"info@evolutionis.com.ar","phone_whatsapp":"",
        "website":"https://evolutionis.com.ar",
        "business":"LED display technology & digital solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":97,"country":"Argentina","region":"South America",
        "company_en":"LetterSystems","company_local":"Letter Systems",
        "city":"Córdoba",
        "contact_name":"Sergio","title":"",
        "email":"sergio@lettersystems.com.ar","phone_whatsapp":"",
        "website":"https://lettersystems.com.ar",
        "business":"LED signage & display systems (Córdoba)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":98,"country":"Argentina","region":"South America",
        "company_en":"Pantalla VIVA","company_local":"Pantalla VIVA",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen rental & events",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":99,"country":"Argentina","region":"South America",
        "company_en":"Fe Publicidad","company_local":"Fe Publicidad",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED outdoor advertising",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":100,"country":"Argentina","region":"South America",
        "company_en":"LED Salta","company_local":"LED Salta",
        "city":"Salta",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen sales & rental (Salta province)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":101,"country":"Argentina","region":"South America",
        "company_en":"Prina Argentina","company_local":"Prina Argentina",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":102,"country":"Argentina","region":"South America",
        "company_en":"7 Sentidos","company_local":"7 Sentidos",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen & sensory experience solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":103,"country":"Argentina","region":"South America",
        "company_en":"SYSTEM ONE","company_local":"SYSTEM ONE",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display & AV system integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":104,"country":"Argentina","region":"South America",
        "company_en":"Audium Argentina","company_local":"Audium",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display & professional audio-visual",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":105,"country":"Argentina","region":"South America",
        "company_en":"LED Screen Argentina","company_local":"LED Screen Argentina",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED screen wholesale & retail",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":106,"country":"Argentina","region":"South America",
        "company_en":"Pantallas LED Argentina","company_local":"Pantallas LED Argentina",
        "city":"Buenos Aires",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED advertising screens; indoor/outdoor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":107,"country":"Argentina","region":"South America",
        "company_en":"Pantallas LED Buenos Aires","company_local":"Pantallas LED Buenos Aires",
        "city":"Buenos Aires, CABA",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display sales & rental (Buenos Aires)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":108,"country":"Argentina","region":"South America",
        "company_en":"Pantallas LED Córdoba","company_local":"Pantallas LED Córdoba",
        "city":"Córdoba",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display sales & rental (Córdoba)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":109,"country":"Argentina","region":"South America",
        "company_en":"Pantallas LED Santa Fe","company_local":"Pantallas LED Santa Fe",
        "city":"Santa Fe",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display sales & rental (Santa Fe province)",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== USA (20) ====================
    {
        "no":110,"country":"USA","region":"North America",
        "company_en":"American LED Display Solutions","company_local":"American LED Display Solutions Corp.",
        "city":"Miami, FL",
        "contact_name":"","title":"",
        "email":"Info@americanledisplays.com",
        "phone_whatsapp":"+1 305-420-5631 / +1 786-228-9212",
        "website":"https://americanledisplays.com",
        "business":"LED visual display mfg/supplier; indoor/outdoor/sports/transparent; global distribution",
        "facebook": "AmericanLedDisplays","instagram": "americanledisplays","linkedin":"linkedin.com/in/american-led-display-solutions-0a116519",
    },
    {
        "no":111,"country":"USA","region":"North America",
        "company_en":"Fusion LED","company_local":"Fusion LED Inc.",
        "city":"Houston, TX",
        "contact_name":"Richard James / Darick Endecott","title":"Founders",
        "email":"sales@fusionled.us","phone_whatsapp":"+1 800-854-6265",
        "website":"https://fusionled.us",
        "business":"LED sign manufacturer; B2B wholesale to sign companies; 1000+ installs",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":112,"country":"USA","region":"North America",
        "company_en":"American LED Technology","company_local":"American LED Technology",
        "city":"North Little Rock, AR",
        "contact_name":"","title":"",
        "email":"info@americanledtechnology.com","phone_whatsapp":"+1 850-863-8777",
        "website":"https://www.americanledtechnology.com",
        "business":"LED display manufacturer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":113,"country":"USA","region":"North America",
        "company_en":"Vanguard LED Displays","company_local":"Vanguard LED Displays",
        "city":"Lakeland, FL",
        "contact_name":"","title":"",
        "email":"info@vanguardled.com","phone_whatsapp":"+1 877-230-8787",
        "website":"https://vanguardled.com",
        "business":"LED display distributor & installer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":114,"country":"USA","region":"North America",
        "company_en":"Aurora LED Systems","company_local":"Aurora LED, LLC",
        "city":"Henderson / Las Vegas, NV",
        "contact_name":"","title":"",
        "email":"info@auroraled.com","phone_whatsapp":"+1 702-386-1088",
        "website":"https://auroraledsystems.com",
        "business":"LED video display; sells to Resellers & Integrators across US & Western Hemisphere",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":115,"country":"USA","region":"North America",
        "company_en":"RP Visual Solutions","company_local":"RP Visual Solutions",
        "city":"Anaheim, CA",
        "contact_name":"","title":"",
        "email":"sales@rpvisuals.com","phone_whatsapp":"+1 714-991-6400",
        "website":"https://rpvisuals.com",
        "business":"LED display & AV visual solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":116,"country":"USA","region":"North America",
        "company_en":"King Size LED","company_local":"King Size LED",
        "city":"Chula Vista, CA",
        "contact_name":"","title":"",
        "email":"info@kingsizeled.com","phone_whatsapp":"+1 619-216-4770",
        "website":"https://www.kingsizeled.com",
        "business":"Large-format LED displays",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":117,"country":"USA","region":"North America",
        "company_en":"LED Craft","company_local":"LED Craft Inc.",
        "city":"St. Louis, MO",
        "contact_name":"","title":"",
        "email":"info@ledcraftinc.com","phone_whatsapp":"+1 314-776-2909",
        "website":"https://www.ledcraftinc.com",
        "business":"LED display manufacturer & distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":118,"country":"USA","region":"North America",
        "company_en":"SNA Displays","company_local":"SNA Displays",
        "city":"New York, NY",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+1 866-848-9149",
        "website":"https://snadisplays.com",
        "business":"Large-scale LED display systems integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":119,"country":"USA","region":"North America",
        "company_en":"PixelFLEX LED","company_local":"PixelFLEX",
        "city":"Nashville, TN",
        "contact_name":"","title":"",
        "email":"sales@pixel-flex.com","phone_whatsapp":"+1 800-930-7954",
        "website":"https://www.pixel-flex.com",
        "business":"Flexible & fine-pitch LED display solutions; entertainment/retail/corporate",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":120,"country":"USA","region":"North America",
        "company_en":"Neoti","company_local":"Neoti",
        "city":"Sioux Falls, SD",
        "contact_name":"","title":"",
        "email":"info@neoti.com","phone_whatsapp":"+1 877-356-3684",
        "website":"https://neoti.com",
        "business":"LED display manufacturer for retail/corporate/broadcast/entertainment",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":121,"country":"USA","region":"North America",
        "company_en":"Formetco","company_local":"Formetco",
        "city":"Duluth, GA",
        "contact_name":"","title":"",
        "email":"sales@formetco.com","phone_whatsapp":"+1 770-476-7000",
        "website":"https://formetco.com",
        "business":"Outdoor LED billboard & digital signage manufacturer (50+ years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":122,"country":"USA","region":"North America",
        "company_en":"NanoLumens","company_local":"NanoLumens",
        "city":"Peachtree Corners, GA",
        "contact_name":"","title":"",
        "email":"info@nanolumens.com","phone_whatsapp":"+1 855-465-8895",
        "website":"https://nanolumens.com",
        "business":"Seamless LED display solutions; retail/hospitality/corporate",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":123,"country":"USA","region":"North America",
        "company_en":"American LED Wall","company_local":"American LED Wall",
        "city":"Houston, TX",
        "contact_name":"","title":"",
        "email":"sales@americanledwall.com","phone_whatsapp":"713-887-2805",
        "website":"https://americanledwall.com",
        "business":"LED video wall sales & installation; events/retail/outdoor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":124,"country":"USA","region":"North America",
        "company_en":"Ultravision LED Solutions","company_local":"Ultravision",
        "city":"Dallas, TX",
        "contact_name":"","title":"",
        "email":"sales@uvledsol.com","phone_whatsapp":"214-504-2404",
        "website":"https://uvledsol.com",
        "business":"Outdoor LED billboard & signage manufacturer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":125,"country":"USA","region":"North America",
        "company_en":"Watchfire Signs","company_local":"Watchfire",
        "city":"Danville, IL",
        "contact_name":"","title":"",
        "email":"sales@watchfire.com","phone_whatsapp":"800-637-2645",
        "website":"https://watchfiresigns.com",
        "business":"LED sign & billboard manufacturer; business/sports/church/transportation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":126,"country":"USA","region":"North America",
        "company_en":"SunRise LED","company_local":"SunRise LED",
        "city":"USA",
        "contact_name":"","title":"",
        "email":"info@sunriseled.com","phone_whatsapp":"800-660-4414",
        "website":"https://sunriseled.com",
        "business":"LED display solutions provider",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":127,"country":"USA","region":"North America",
        "company_en":"Vantage LED","company_local":"Vantage LED",
        "city":"Ontario, CA",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"888-595-3956",
        "website":"https://vantageled.com",
        "business":"Outdoor LED digital signage manufacturer",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":128,"country":"USA","region":"North America",
        "company_en":"Advision LED Signs","company_local":"Advision LED Signs",
        "city":"Oakdale, CA",
        "contact_name":"","title":"",
        "email":"contact@advisionledsigns.com","phone_whatsapp":"+1 877-532-5593",
        "website":"https://advisionledsigns.com",
        "business":"LED sign solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":129,"country":"USA","region":"North America",
        "company_en":"Cirrus LED","company_local":"Cirrusled",
        "city":"Portsmouth, NH",
        "contact_name":"","title":"",
        "email":"info@cirrusled.com","phone_whatsapp":"+1 877-636-2331",
        "website":"https://www.cirrusled.com",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== CANADA (1) ====================
    {
        "no":130,"country":"Canada","region":"North America",
        "company_en":"Christie Digital Systems","company_local":"Christie Digital Systems",
        "city":"Kitchener, ON",
        "contact_name":"","title":"",
        "email":"info@christiedigital.com","phone_whatsapp":"+1 714-527-7056",
        "website":"https://www.christiedigital.com",
        "business":"Large-format display & video wall mfg; wholesale to resellers/integrators",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== MEXICO (12 → 21) ====================
    {
        "no":131,"country":"Mexico","region":"North America",
        "company_en":"RGB Tronics","company_local":"RGB Tronics",
        "city":"Monterrey, NL",
        "contact_name":"","title":"",
        "email":"info@rgbtronics.com.mx","phone_whatsapp":"+52 81 1772-4695",
        "website":"https://rgbtronics.com.mx",
        "business":"Giant LED screen wholesale & retail, 10+ years",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":132,"country":"Mexico","region":"North America",
        "company_en":"DMX Technologies","company_local":"DMX TEC",
        "city":"Mexico City",
        "contact_name":"","title":"",
        "email":"info@dmxtec.com","phone_whatsapp":"+52 55 5662-2600",
        "website":"https://pantallasled.mx",
        "business":"Large-scale LED electronic screen wholesaler, 10+ years",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":133,"country":"Mexico","region":"North America",
        "company_en":"iLED Mexico","company_local":"iLED Mexico",
        "city":"Monterrey, NL",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+52 81 1101-5015",
        "website":"https://www.iled.com.mx",
        "business":"Giant advertising screens: curved/outdoor/mobile; engineering/installation/maintenance",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":134,"country":"Mexico","region":"North America",
        "company_en":"Medios Mexico","company_local":"Medios México",
        "city":"Naucalpan, Estado de Mexico",
        "contact_name":"","title":"",
        "email":"info@mediosmexico.com","phone_whatsapp":"+52 55 5293-2000",
        "website":"http://mediosmexico.com",
        "business":"LED screen commercialization, manufacturing & outdoor digital advertising, 10+ yrs",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":135,"country":"Mexico","region":"North America",
        "company_en":"HPMLED / Grupo Vision","company_local":"HPMLED",
        "city":"Apodaca, Nuevo León",
        "contact_name":"","title":"",
        "email":"aguzman@grupovision.com.mx","phone_whatsapp":"+52 81 1158-5800",
        "website":"https://hpmled.com.mx",
        "business":"LED display solutions, industrial park",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":136,"country":"Mexico","region":"North America",
        "company_en":"Pixel Window Mexico","company_local":"Pixelwindow",
        "city":"Zapopan, Jalisco",
        "contact_name":"E. Barón","title":"",
        "email":"ebaron@pixelwindow.com.mx","phone_whatsapp":"+52 442 456-4968",
        "website":"https://www.pixelwindow.com.mx",
        "business":"LED display manufacturer; CDMX / Querétaro / Guadalajara offices",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":137,"country":"Mexico","region":"North America",
        "company_en":"Showco Mexico","company_local":"Showco",
        "city":"Naucalpan, Estado de Mexico",
        "contact_name":"","title":"",
        "email":"info@showco.com.mx","phone_whatsapp":"+52 55 5000-9480",
        "website":"https://www.showco.com.mx",
        "business":"LED screens, events & AV",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":138,"country":"Mexico","region":"North America",
        "company_en":"MAX Signage Mexico","company_local":"MAX Signage",
        "city":"Mexico City",
        "contact_name":"Ricardo Zepeda","title":"",
        "email":"ricardo.zepeda@max-signage.com.mx","phone_whatsapp":"+52 55 5021-3584",
        "website":"https://max-signage.com.mx",
        "business":"LED signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":139,"country":"Mexico","region":"North America",
        "company_en":"Luft Screen","company_local":"Luft Screen",
        "city":"Iztacalco, CDMX",
        "contact_name":"","title":"",
        "email":"informes@luftscreen.com.mx","phone_whatsapp":"+52 1 55 2335-3227",
        "website":"https://luftscreen.com.mx",
        "business":"LED screen solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":140,"country":"Mexico","region":"North America",
        "company_en":"SAP LED","company_local":"SAP LED",
        "city":"San Luis Potosí",
        "contact_name":"","title":"",
        "email":"contacto@sapled.mx","phone_whatsapp":"+52 444 210-0824",
        "website":"https://sapled.mx",
        "business":"LED display distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":141,"country":"Mexico","region":"North America",
        "company_en":"Eyecatch Mexico","company_local":"Eyecatch Mexico",
        "city":"Mexico City",
        "contact_name":"Eduardo Rosales","title":"",
        "email":"eduardo.rosales@eyecatch.mx","phone_whatsapp":"+52 56 1004-6498",
        "website":"https://eyecatch.mx",
        "business":"LED display & digital signage",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":142,"country":"Mexico","region":"North America",
        "company_en":"MMP Screen","company_local":"MMP Screen",
        "city":"Roma Sur, CDMX",
        "contact_name":"","title":"",
        "email":"info@mmp.com.mx","phone_whatsapp":"+52 55 5412-0445",
        "website":"https://mmp.com.mx",
        "business":"LED screen solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Mexico companies (v4) ---
    {
        "no":143,"country":"Mexico","region":"North America",
        "company_en":"Pantallas LED Mexico","company_local":"Pantallas LED",
        "city":"Mexico City",
        "contact_name":"","title":"",
        "email":"sales@ledscreens.com.mx","phone_whatsapp":"",
        "website":"https://ledscreens.com.mx",
        "business":"LED screen wholesale, advertising & events",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":144,"country":"Mexico","region":"North America",
        "company_en":"Lumtec Mexico","company_local":"Lumtec",
        "city":"Mexico",
        "contact_name":"","title":"",
        "email":"info@lumtec.com.mx","phone_whatsapp":"",
        "website":"https://lumtec.com.mx",
        "business":"LED display solutions & lighting technology",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":145,"country":"Mexico","region":"North America",
        "company_en":"M&S Media Mexico","company_local":"M&S Media",
        "city":"Mexico",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED display & media solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":146,"country":"Mexico","region":"North America",
        "company_en":"Visual Stage Mexico","company_local":"Visual Stage",
        "city":"Mexico",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"",
        "business":"LED stage & event display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":147,"country":"Mexico","region":"North America",
        "company_en":"VideoWall Mexico","company_local":"VideoWall.com.mx",
        "city":"Mexico",
        "contact_name":"","title":"",
        "email":"info@videowall.com.mx","phone_whatsapp":"",
        "website":"https://videowall.com.mx",
        "business":"LED video wall sales & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":148,"country":"Mexico","region":"North America",
        "company_en":"Kolo Digital","company_local":"Kolo Digital",
        "city":"Mexico",
        "contact_name":"","title":"",
        "email":"contacto@kolo.digital","phone_whatsapp":"",
        "website":"https://kolo.digital",
        "business":"Digital LED display & signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":149,"country":"Mexico","region":"North America",
        "company_en":"POLIEDRO DIGITAL","company_local":"Poliedro Digital",
        "city":"Mexico",
        "contact_name":"","title":"",
        "email":"ventas@poliedrodigital.com.mx","phone_whatsapp":"",
        "website":"https://poliedrodigital.com.mx",
        "business":"LED display solutions; indoor/outdoor advertising",
        "facebook":"","instagram":"","linkedin":"",
    },
    # ==================== KOREA (29 → 58) ====================
    {
        "no":150,"country":"Korea","region":"Asia",
        "company_en":"RGB Korea","company_local":"RGB Korea / RGB코리아",
        "city":"Siheung, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"amnite@naver.com","phone_whatsapp":"+82 31 504-3773",
        "website":"https://rgbkorea.com",
        "business":"Transparent LED screen, LED lighting, media facade, theme park lighting",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":151,"country":"Korea","region":"Asia",
        "company_en":"MD LED Innovation","company_local":"MD LED 이노베이션",
        "city":"Hwaseong, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"mdledinnovation@naver.com","phone_whatsapp":"+82 31 356-1121",
        "website":"https://www.mdledinnovation.com",
        "business":"Indoor/outdoor/vehicle/hologram/transparent/media facade LED (since 1990)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":152,"country":"Korea","region":"Asia",
        "company_en":"Galaxia Electronics","company_local":"갤럭시아일렉트로닉스",
        "city":"Suwon, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 31 806-0897",
        "website":"https://eng.galaxialed.com",
        "business":"LED display manufacturer (since 2014)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":153,"country":"Korea","region":"Asia",
        "company_en":"KODICO","company_local":"코디코",
        "city":"Ansan, Gyeonggi-do",
        "contact_name":"Thomas Yoo","title":"International Sales",
        "email":"Thomas.yoo@kodico.co.kr","phone_whatsapp":"+82 70 4681-6149",
        "website":"https://kodico.co.kr/eng",
        "business":"LED display solutions (since 1990)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":154,"country":"Korea","region":"Asia",
        "company_en":"Kinoton Korea","company_local":"키노톤코리아",
        "city":"Seoul (Seocho-gu)",
        "contact_name":"","title":"",
        "email":"biz@kinoton.co.kr","phone_whatsapp":"+82 2 6923-1900",
        "website":"https://kinoton.co.kr",
        "business":"LED/video/digital media/audio solutions; cinema & events",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":155,"country":"Korea","region":"Asia",
        "company_en":"Samik Electronics","company_local":"삼익전자",
        "city":"Seoul (Gangnam-gu)",
        "contact_name":"","title":"",
        "email":"samilk@samikdisplay.co.kr","phone_whatsapp":"+82 2 510-2000",
        "website":"https://samikdisplay.co.kr",
        "business":"LED display pioneer in Korea (since 1969); indoor/outdoor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":156,"country":"Korea","region":"Asia",
        "company_en":"ARA System","company_local":"아라시스템",
        "city":"Anyang, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"info@arasystem.kr","phone_whatsapp":"+82 70 4895-0794",
        "website":"https://arasystem.kr",
        "business":"LED display system integrator (since 2007)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":157,"country":"Korea","region":"Asia",
        "company_en":"ShownProbe","company_local":"쇼운프로브",
        "city":"Goyang, Gyeonggi-do (KINTEX area)",
        "contact_name":"","title":"",
        "email":"info@shownprove.co.kr","phone_whatsapp":"+82 70 0054-1712",
        "website":"https://www.shownprove.co.kr",
        "business":"Indoor & outdoor LED screens; events & fixed installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":158,"country":"Korea","region":"Asia",
        "company_en":"AVAVISION","company_local":"아바비전",
        "city":"Anyang, Gyeonggi-do",
        "contact_name":"박재준 (Park Jae-Jun)","title":"CEO",
        "email":"sales@avavision.co.kr","phone_whatsapp":"+82 31 443-3311",
        "website":"https://www.avavision.co.kr",
        "business":"Commercial LED screen integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":159,"country":"Korea","region":"Asia",
        "company_en":"KOSES","company_local":"코세스",
        "city":"Guri, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"mara107@naver.com","phone_whatsapp":"+82 2 470-1156",
        "website":"https://coses.co.kr",
        "business":"Outdoor LED screen (since 2004)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":160,"country":"Korea","region":"Asia",
        "company_en":"ILLIES","company_local":"일리스",
        "city":"Seoul (Yongsan-gu)",
        "contact_name":"","title":"",
        "email":"illis@illis.co.kr","phone_whatsapp":"+82 2 971-1215",
        "website":"https://illis.co.kr",
        "business":"Indoor/fixed LED screen solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":161,"country":"Korea","region":"Asia",
        "company_en":"Daesung LED","company_local":"대성LED",
        "city":"Gwangmyeong, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"ygh5680@naver.com","phone_whatsapp":"+82 1544-9647",
        "website":"https://daesungled.com",
        "business":"Commercial LED screen",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":162,"country":"Korea","region":"Asia",
        "company_en":"Basic Tech","company_local":"베이직테크",
        "city":"Paju, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"basic@basictech.co.kr","phone_whatsapp":"+82 70 7004-2200",
        "website":"https://basictech.co.kr",
        "business":"Commercial LED display (since 1996)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":163,"country":"Korea","region":"Asia",
        "company_en":"Shinwoo SNC","company_local":"신우에스앤씨",
        "city":"Seoul (Geumcheon-gu)",
        "contact_name":"임 권 (Lim Kwon)","title":"CEO",
        "email":"webmaster@shinwoosnc.com","phone_whatsapp":"+82 2 701-2787",
        "website":"https://swsled.co.kr",
        "business":"Indoor/outdoor LED; rental LED; 20+ service centers nationwide",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":164,"country":"Korea","region":"Asia",
        "company_en":"Neulsom LED","company_local":"늘솜LED",
        "city":"Siheung, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 31 487-7812",
        "website":"https://www.nsled.kr",
        "business":"Rental LED screen specialist",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":165,"country":"Korea","region":"Asia",
        "company_en":"Winmeditech","company_local":"윈미디텍",
        "city":"Seoul (Yeongdeungpo-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 3272-3939",
        "website":"https://winmedi.co.kr",
        "business":"Commercial LED display, AV integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":166,"country":"Korea","region":"Asia",
        "company_en":"Primemedia Korea","company_local":"프라임미디어",
        "city":"Goyang, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 754-0004",
        "website":"https://www.primemedia.co.kr",
        "business":"Rental LED screen; events & corporate",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":167,"country":"Korea","region":"Asia",
        "company_en":"TAG Solution","company_local":"TAG솔루션",
        "city":"Seoul (Gwanak-gu)",
        "contact_name":"","title":"",
        "email":"imnews178@naver.com","phone_whatsapp":"+82 10 3062-1050",
        "website":"https://tagsolution.kr",
        "business":"Transparent & rental LED screens",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":168,"country":"Korea","region":"Asia",
        "company_en":"Mpartners","company_local":"엠파트너스",
        "city":"Seoul (Yeongdeungpo-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 3281-9660",
        "website":"https://mpartners.co.kr",
        "business":"Commercial LED display distributor",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":169,"country":"Korea","region":"Asia",
        "company_en":"RAON VISUAL","company_local":"라온비주얼",
        "city":"Seoul (Seongdong-gu)",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 2088-7626",
        "website":"https://www.raonvisual.co.kr",
        "business":"Commercial LED screen integrator",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":170,"country":"Korea","region":"Asia",
        "company_en":"ADEG Korea","company_local":"에이덱",
        "city":"Seoul (Yongsan-gu)",
        "contact_name":"","title":"",
        "email":"adeg1@naver.com","phone_whatsapp":"+82 70 8866-8144",
        "website":"https://www.adeg.co.kr",
        "business":"Indoor/outdoor fixed LED screens",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":171,"country":"Korea","region":"Asia",
        "company_en":"VISSEM","company_local":"비쎔",
        "city":"Yongin, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 31 288-3428",
        "website":"https://www.vissem.com",
        "business":"Outdoor LED screen",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":172,"country":"Korea","region":"Asia",
        "company_en":"Kiosk Korea","company_local":"키오스크코리아",
        "city":"Seoul (Geumcheon-gu)",
        "contact_name":"","title":"",
        "email":"help@kioskkorea.kr","phone_whatsapp":"+82 70 8623-1525",
        "website":"https://kioskkorea.com",
        "business":"LED kiosk & digital signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":173,"country":"Korea","region":"Asia",
        "company_en":"D-King LED","company_local":"디킹LED",
        "city":"Seoul",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"https://dkingdisplay.com",
        "business":"XR LED / naked-eye 3D / stage rental LED / digital signage (20 years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":174,"country":"Korea","region":"Asia",
        "company_en":"JBDISPLAY","company_local":"JB디스플레이",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"https://www.jbdisplay.co.kr",
        "business":"LED display + digital signage; planning/R&D/mfg/installation (30+ years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":175,"country":"Korea","region":"Asia",
        "company_en":"Shinelight","company_local":"주식회사 샤인라이트",
        "city":"Asan, Chungcheongnam-do / Suwon, Gyeonggi-do",
        "contact_name":"김현진 (Kim Hyun-jin)","title":"CEO",
        "email":"led@shinelight.kr","phone_whatsapp":"+82 1666-1548",
        "website":"https://shinelight.kr",
        "business":"Indoor/outdoor LED display; transparent screen; media facade",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":176,"country":"Korea","region":"Asia",
        "company_en":"SYSMATE","company_local":"주식회사 시스메이트",
        "city":"Seoul (Geumcheon-gu)",
        "contact_name":"정종균 (Jung Jong-gyun)","title":"CEO",
        "email":"sysmate@sysmate.co.kr","phone_whatsapp":"+82 1833-9009",
        "website":"https://sysmate.co.kr",
        "business":"LED display system integration & installation",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":177,"country":"Korea","region":"Asia",
        "company_en":"Koled","company_local":"주식회사 코레드",
        "city":"Ansan, Gyeonggi-do",
        "contact_name":"이영훈 (Lee Young-hoon)","title":"CEO",
        "email":"","phone_whatsapp":"+82 31 478-5330 / 010-6791-7212",
        "website":"https://koled.co.kr",
        "business":"LED display wholesale & distribution",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":178,"country":"Korea","region":"Asia",
        "company_en":"Asolcompany","company_local":"아솔컴퍼니",
        "city":"Seoul (Dongdaemun-gu)",
        "contact_name":"정경식 (Jeong Gyeong-sik)","title":"CEO",
        "email":"itsolu@naver.com","phone_whatsapp":"+82 2 1544-7581",
        "website":"",
        "business":"LED display installation & integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    # --- New Korea companies (v4) ---
    {
        "no":179,"country":"Korea","region":"Asia",
        "company_en":"TRL Korea","company_local":"TRL코리아",
        "city":"Gimpo, Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"trl_sales@naver.com","phone_whatsapp":"+82 31 977-6114",
        "website":"",
        "business":"LED display sales & integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":180,"country":"Korea","region":"Asia",
        "company_en":"D'STRICT","company_local":"디스트릭트",
        "city":"Seoul",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 515-5456",
        "website":"https://dstrict.com",
        "business":"Immersive LED media art & XR content; AMOLED Wave / naked-eye 3D",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":181,"country":"Korea","region":"Asia",
        "company_en":"DFlux Global","company_local":"디플럭스글로벌",
        "city":"Gyeonggi-do",
        "contact_name":"","title":"",
        "email":"dflux@dfluxglobal.com","phone_whatsapp":"+82 31 987-6540",
        "website":"https://dfluxglobal.com",
        "business":"LED display global solutions & supply",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":182,"country":"Korea","region":"Asia",
        "company_en":"JDKAT","company_local":"제이디케이에이티",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"jdk@jdkat.com","phone_whatsapp":"+82 50 7875-0750",
        "website":"",
        "business":"LED display solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":183,"country":"Korea","region":"Asia",
        "company_en":"Bandyled","company_local":"반딧불LED",
        "city":"Daegu",
        "contact_name":"김종수 (Kim Jong-su)","title":"CEO",
        "email":"bandyled@bandyled.com","phone_whatsapp":"+82 1544-8170",
        "website":"https://bandyled.com",
        "business":"Indoor/outdoor LED display; Daegu region specialist",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":184,"country":"Korea","region":"Asia",
        "company_en":"AV Team","company_local":"에이브이팀",
        "city":"Changwon, South Gyeongsang",
        "contact_name":"","title":"",
        "email":"avteam2016@naver.com","phone_whatsapp":"+82 1544-0476",
        "website":"",
        "business":"LED display & AV solutions (Changwon/Gyeongnam region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":185,"country":"Korea","region":"Asia",
        "company_en":"CUDO Communication","company_local":"쿠도커뮤니케이션",
        "city":"Seoul (Seocho-gu)",
        "contact_name":"","title":"",
        "email":"hhj7518@cudo.co.kr","phone_whatsapp":"+82 2 525-0473",
        "website":"https://cudo.co.kr",
        "business":"Digital signage & LED display integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":186,"country":"Korea","region":"Asia",
        "company_en":"xtrmGROUP","company_local":"익스트림그룹",
        "city":"Incheon (Songdo)",
        "contact_name":"","title":"",
        "email":"lsh@dicodp.com","phone_whatsapp":"+82 2 2102-8574",
        "website":"https://xtrmgroup.co.kr",
        "business":"LED display & digital solutions (Songdo Incheon)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":187,"country":"Korea","region":"Asia",
        "company_en":"KSYS","company_local":"케이시스",
        "city":"Busan",
        "contact_name":"천병민 (Cheon Byeong-min)","title":"CEO",
        "email":"","phone_whatsapp":"+82 1600-6187",
        "website":"",
        "business":"LED display solutions (Busan region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":188,"country":"Korea","region":"Asia",
        "company_en":"Rica Holdings","company_local":"리카홀딩스",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 10 3950-3678",
        "website":"",
        "business":"LED display & technology holdings",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":189,"country":"Korea","region":"Asia",
        "company_en":"Yap Media","company_local":"얍미디어",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"yapmedia@naver.com","phone_whatsapp":"",
        "website":"",
        "business":"LED media & digital signage solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":190,"country":"Korea","region":"Asia",
        "company_en":"Lzon","company_local":"엘존",
        "city":"Daegu",
        "contact_name":"","title":"",
        "email":"mail@lzone.co.kr","phone_whatsapp":"+82 53 625-5966",
        "website":"",
        "business":"LED display solutions (Daegu region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":191,"country":"Korea","region":"Asia",
        "company_en":"FlyNurse","company_local":"플라이너스",
        "city":"Seoul",
        "contact_name":"","title":"",
        "email":"flynurse@flynurse.kr","phone_whatsapp":"+82 2 322-0132",
        "website":"",
        "business":"LED display & digital media solutions",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":192,"country":"Korea","region":"Asia",
        "company_en":"Zion LED","company_local":"지온LED",
        "city":"Incheon",
        "contact_name":"","title":"",
        "email":"beauti430@daum.net","phone_whatsapp":"+82 10 4682-3141",
        "website":"",
        "business":"LED display sales & installation (Incheon area)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":193,"country":"Korea","region":"Asia",
        "company_en":"Evix Korea / AVICS","company_local":"에빅스코리아",
        "city":"Seoul",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 322-3264",
        "website":"",
        "business":"LED display & AV integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":194,"country":"Korea","region":"Asia",
        "company_en":"SHOPGET","company_local":"샵겟",
        "city":"Daegu",
        "contact_name":"","title":"",
        "email":"imnews178@naver.com","phone_whatsapp":"+82 10 3062-1050",
        "website":"",
        "business":"LED display retail & installation (Daegu)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":195,"country":"Korea","region":"Asia",
        "company_en":"Guide Samjeong","company_local":"가이드삼정",
        "city":"Seoul (Yeongdeungpo-gu)",
        "contact_name":"문용만 (Moon Yong-man)","title":"CEO",
        "email":"lye@guidesamjung.co.kr","phone_whatsapp":"+82 2 780-2323",
        "website":"",
        "business":"LED display system integration & consulting",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":196,"country":"Korea","region":"Asia",
        "company_en":"Hyosung ITX","company_local":"효성ITX",
        "city":"Seoul",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 2 2102-8400",
        "website":"https://hyosungitx.com",
        "business":"LED display & IT solutions integration",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":197,"country":"Korea","region":"Asia",
        "company_en":"MEM System","company_local":"엠이엠시스템",
        "city":"Gwangju",
        "contact_name":"장영직 (Jang Yeong-jik)","title":"CEO",
        "email":"","phone_whatsapp":"+82 31 798-7200",
        "website":"",
        "business":"LED display system solutions (Gwangju/Gyeonggi region)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":198,"country":"Korea","region":"Asia",
        "company_en":"Daol C&C","company_local":"다올씨앤씨",
        "city":"Incheon",
        "contact_name":"김승용 (Kim Seung-yong)","title":"CEO",
        "email":"","phone_whatsapp":"+82 32 363-3470",
        "website":"",
        "business":"LED display construction & maintenance (Incheon)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":199,"country":"Korea","region":"Asia",
        "company_en":"TREEM","company_local":"트리엠",
        "city":"Seoul",
        "contact_name":"김동수 (Kim Dong-su)","title":"CEO",
        "email":"","phone_whatsapp":"+82 2 2024-1900",
        "website":"",
        "business":"LED display solutions & media technology",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":200,"country":"Korea","region":"Asia",
        "company_en":"Eloi Media","company_local":"엘로이미디어",
        "city":"Busan",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 70 4060-1001",
        "website":"",
        "business":"LED display & media solutions (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":201,"country":"Korea","region":"Asia",
        "company_en":"Daniel System","company_local":"다니엘시스템",
        "city":"Busan",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 1644-3350",
        "website":"",
        "business":"LED display system integration (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":202,"country":"Korea","region":"Asia",
        "company_en":"LED Sign Art","company_local":"엘이디싸인아트",
        "city":"Busan",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 51 316-8567",
        "website":"",
        "business":"LED signage & display art (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":203,"country":"Korea","region":"Asia",
        "company_en":"SNTech","company_local":"에스엔테크",
        "city":"Busan",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 51 531-0881",
        "website":"",
        "business":"LED display technology solutions (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":204,"country":"Korea","region":"Asia",
        "company_en":"Soo Woo","company_local":"수우",
        "city":"Busan",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"+82 51 504-3558",
        "website":"",
        "business":"LED display sales & installation (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":205,"country":"Korea","region":"Asia",
        "company_en":"SUNLED","company_local":"썬엘이디",
        "city":"Busan",
        "contact_name":"오기성 (Oh Ki-seong)","title":"CEO",
        "email":"","phone_whatsapp":"+82 1566-3346",
        "website":"",
        "business":"LED display manufacturer & distributor (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":206,"country":"Korea","region":"Asia",
        "company_en":"Namwoong Electronics","company_local":"남웅전자",
        "city":"Busan",
        "contact_name":"","title":"",
        "email":"nw119@naver.com","phone_whatsapp":"+82 51 804-0660",
        "website":"",
        "business":"LED display electronics (Busan)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":207,"country":"Korea","region":"Asia",
        "company_en":"MLS Korea","company_local":"엠엘에스",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"https://www.led-mls.com/ko/",
        "business":"LED display manufacturer; outdoor billboard/rental/events/stadium/broadcast",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":208,"country":"Korea","region":"Asia",
        "company_en":"Daehan LED (대한전광)","company_local":"대한전광",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"http://dhutr.com/",
        "business":"Outdoor/indoor/building facade/stadium LED (40 years)",
        "facebook":"","instagram":"","linkedin":"",
    },
    {
        "no":209,"country":"Korea","region":"Asia",
        "company_en":"MICLED","company_local":"미크레드",
        "city":"Korea",
        "contact_name":"","title":"",
        "email":"","phone_whatsapp":"",
        "website":"https://micled.tech/",
        "business":"LED control system, video processing, Micro LED revolution",
        "facebook":"","instagram":"","linkedin":"",
    },
]

# ─── Workbook ─────────────────────────────────────────────────────────────────
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "LED Leads - All Markets"

COLOR_HEADER_BG   = "1F4E79"
COLOR_HEADER_FONT = "FFFFFF"

COUNTRY_COLORS = {
    "Brazil":    "D9EAD3",
    "Colombia":  "FCE5CD",
    "Chile":     "D0E4F5",
    "Peru":      "FFF2CC",
    "Argentina": "EAD1DC",
    "USA":       "CFE2F3",
    "Canada":    "E6D0DE",
    "Mexico":    "D9D2E9",
    "Korea":     "F4CCCC",
}

headers = [
    "No.", "Region", "Country", "City",
    "Company (English)", "Company (Local Language)",
    "Contact Person", "Title",
    "Email", "Phone / WhatsApp / Kakao",
    "Website", "Main Business",
    "Facebook", "Instagram", "LinkedIn",
    "Notes / Action",
]

thin = Side(style="thin", color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

hfill  = PatternFill("solid", fgColor=COLOR_HEADER_BG)
hfont  = Font(bold=True, color=COLOR_HEADER_FONT, size=11)
halign = Alignment(horizontal="center", vertical="center", wrap_text=True)

for ci, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=ci, value=h)
    cell.fill = hfill; cell.font = hfont
    cell.alignment = halign; cell.border = border
ws.row_dimensions[1].height = 36

for ri, lead in enumerate(leads, 2):
    row_data = [
        lead["no"], lead["region"], lead["country"], lead["city"],
        lead["company_en"], lead["company_local"],
        lead["contact_name"], lead["title"],
        lead["email"], lead["phone_whatsapp"],
        lead["website"], lead["business"],
        lead["facebook"], lead["instagram"], lead["linkedin"],
        "",  # Notes
    ]
    rfill = PatternFill("solid", fgColor=COUNTRY_COLORS.get(lead["country"], "FFFFFF"))
    for ci, val in enumerate(row_data, 1):
        cell = ws.cell(row=ri, column=ci, value=val)
        cell.fill = rfill
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        cell.border = border
    ws.row_dimensions[ri].height = 26

col_widths = [5, 14, 12, 25, 28, 28, 18, 14, 32, 32, 34, 50, 32, 30, 42, 20]
for ci, w in enumerate(col_widths, 1):
    ws.column_dimensions[get_column_letter(ci)].width = w
ws.freeze_panes = "A2"

# ─── Summary sheet ────────────────────────────────────────────────────────────
ws2 = wb.create_sheet("Summary")
ws2["A1"] = "LED Display Leads — Americas + Korea  (v4)"
ws2["A1"].font = Font(bold=True, size=14, color=COLOR_HEADER_BG)

ws2["A3"] = "Region"; ws2["B3"] = "Country"; ws2["C3"] = "# Companies"
for cell in ws2["A3:C3"][0]:
    cell.fill = hfill; cell.font = hfont
    cell.alignment = Alignment(horizontal="center")

country_count = Counter(lead["country"] for lead in leads)

summary = [
    ("South America", "Brazil",    country_count["Brazil"]),
    ("South America", "Colombia",  country_count["Colombia"]),
    ("South America", "Chile",     country_count["Chile"]),
    ("South America", "Peru",      country_count["Peru"]),
    ("South America", "Argentina", country_count["Argentina"]),
    ("North America", "USA",       country_count["USA"]),
    ("North America", "Canada",    country_count["Canada"]),
    ("North America", "Mexico",    country_count["Mexico"]),
    ("Asia",          "Korea",     country_count["Korea"]),
]
for i, (region, country, cnt) in enumerate(summary, 4):
    ws2.cell(row=i, column=1, value=region)
    ws2.cell(row=i, column=2, value=country)
    ws2.cell(row=i, column=3, value=cnt)
    f = PatternFill("solid", fgColor=COUNTRY_COLORS.get(country, "FFFFFF"))
    for c in range(1, 4):
        ws2.cell(row=i, column=c).fill = f

total_row = len(summary) + 4
ws2.cell(row=total_row, column=1, value="TOTAL")
ws2.cell(row=total_row, column=3, value=sum(r[2] for r in summary))
for c in range(1, 4):
    ws2.cell(row=total_row, column=c).font = Font(bold=True)

for col in ["A","B","C"]:
    ws2.column_dimensions[col].width = 22

# ─── Tips sheet ───────────────────────────────────────────────────────────────
ws3 = wb.create_sheet("开发建议")
tips = [
    ("优先级", "建议"),
    ("★★★ 立即联系", "WhatsApp直接发开发消息（南美市场首选渠道）"),
    ("★★★ 立即联系", "有邮箱的公司发英语+当地语言双语开发信"),
    ("★★ 深挖联系人", "通过LinkedIn搜索公司的采购/老板职位 (Gerente/Compras/Procurement)"),
    ("★★ 社媒触达", "INS/Facebook发DM，附产品图+报价意向"),
    ("★ 后续跟进", "韩国公司建议英文邮件 + 附韩文简介，有CEO姓名直接点名联系"),
    ("注意", "South America: WhatsApp是主战场，不要只发邮件"),
    ("注意", "巴西公司联系语言优先葡萄牙语，其他南美优先西班牙语"),
    ("注意", "韩国公司多为中端集成商/安装商，适合推广中等价位产品"),
    ("注意", "Korea: 有CEO名字的公司优先联系，直接写 Dear Mr./Ms. XXX"),
    ("注意", "釜山集群(Busan): 051开头电话，可批量开发同城商家"),
    ("注意", "大邱集群(Daegu): 053开头电话，LED屏集中地区"),
]
ws3["A1"] = "客户开发执行建议"
ws3["A1"].font = Font(bold=True, size=13, color=COLOR_HEADER_BG)
ws3.merge_cells("A1:B1")
for i, (priority, tip) in enumerate(tips, 3):
    ws3.cell(row=i, column=1, value=priority).font = Font(bold=(i==3))
    ws3.cell(row=i, column=2, value=tip)
ws3.column_dimensions["A"].width = 20
ws3.column_dimensions["B"].width = 65

out = r"C:\Users\Administrator\ai-topic-generator\output\leads\LED_Display_Leads_v4.xlsx"
wb.save(out)
print(f"Saved: {out}")
print(f"Total records: {len(leads)}")
for region, country, cnt in summary:
    print(f"  {country}: {cnt}")
print(f"  TOTAL: {sum(r[2] for r in summary)}")
